### ISSUE TITLE
save_to_file

### ISSUE THREAD

**Issue by eco79** [Significant-Gravitas/Auto-GPT#1000]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

In a complex task, some of the agents need to write to a file. They are always failing with this error:
`Command save_to_file returned: Unknown command 'save_to_file'.`

### Current behavior 😯

It throws the error and continues.

### Expected behavior 🤔

It should write to file or give a better error message by explaining why it can't write or a possible solution

### Your prompt 📝

```yaml
ai_goals:
- Discover the oldest recipes in different categories.The categories are the ones you find usualy in cookbooks.
- Plan the cookbook to contain at least 5 recipes for each category. 
- Write the book autonomously.
- Play to your strengths as a Large Language Model.
ai_name: Tati-GPT
ai_role: an AI designed to autonomously analyse, plan and write a cookbook about the oldest recipes from the Tigres and Euphrates area.
```
