### ISSUE TITLE
Infinite loop with Error while `execute_python_file`

### ISSUE THREAD

**Issue by Artemonim** [Significant-Gravitas/Auto-GPT#1018]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Ask to write the application in Python and wait until Auto-GPT wants to run it for testing
`--gpt3only`
commit-hash: `5982f29c18e8efcac00676afa653334f8845ada9`, master branch

### Current behavior 😯

[A similar problem was first described in Discord back on 05.04.2023](https://discord.com/channels/1092243196446249134/1092275629602394184/1093218252148199465)
```bash
Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
```
He tries to find a solution, but basically keeps trying to use `execute_python_file`

### Expected behavior 🤔

run the script

### Your prompt 📝

```yaml
ai_goals:
- "Create a window with a title, a display area and buttons for digits and operations using the Tkinter library"
- "Define and bind functions for each button to update the display and perform calculations"
- "Write a report about the work done, the challenges faced and the lessons learned."
ai_name: Auto-GPT Developer
ai_role: "Create a simple calculator program using built-in Python libraries. Record your actions in the files.
  Save the code that you create to files. Write a report about the work done."
```
