### ISSUE TITLE
Empty Response - JSON Error

### ISSUE THREAD

**Issue by RocketNinja15** [Significant-Gravitas/Auto-GPT#1254]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Use my prompt on gpt3 mode.

### Current behavior 😯

NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'Web Design Agent', 'task': 'Draft main features and design of website', 'prompt': 'Please draft the main features and design of website based on the search results and what you have learned about user-friendly design.'}
SYSTEM:  Command start_agent returned: Agent Web Design Agent created with key 1. First response: Before we discuss the main features and design of your website based on the search results, please provide me with more context and details about your business, target audience, and goals for the website. This information will help me create a custom and effective design that meets your specific needs and requirements.
ENTREPRENEUR-GPT THOUGHTS: 
REASONING: 
CRITICISM: 
Attempting to fix JSON by finding outermost brackets 
Apparently json was fixed. 
NEXT ACTION:  COMMAND = Error: ARGUMENTS = Missing 'command' object in JSON
SYSTEM:  Command Error: threw the following error: Missing 'command' object in JSON
/ Thinking... 

### Expected behavior 🤔

Should not return an error/blank

### Your prompt 📝

```yaml
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: Entrepreneur-GPT
Entrepreneur-GPT here!  I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
Entrepreneur-GPT is: an AI designed to autonomously create and run a new businesness through coding a website with the sole goal of creating profit.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: Find Profitable Website Ideas'
Goal 2: Code a Profitable Website  
Goal 3: Develop and manage the website autonomously
Goal 4: Publish the website and get traffic/sales/profit to it
Goal 5: don't get distracted and complete in the most efficient way
Using memory of type: LocalCache
```
