### ISSUE TITLE
error when given goals

### ISSUE THREAD

**Issue by bxvlz2** [Significant-Gravitas/Auto-GPT#1556]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

start Auto-GPT and give your name and goals

### Current behavior 😯

an error is given: Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\bxvlz\Desktop\autogpt\Auto-GPT\autogpt\__main__.py", line 572, in <module>
    main()
  File "C:\Users\bxvlz\Desktop\autogpt\Auto-GPT\autogpt\__main__.py", line 396, in main
    agent.start_interaction_loop()
  File "C:\Users\bxvlz\Desktop\autogpt\Auto-GPT\autogpt\__main__.py", line 448, in start_interaction_loop
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\bxvlz\Desktop\autogpt\Auto-GPT\autogpt\chat.py", line 159, in chat_with_ai
    assistant_reply = create_chat_completion(
  File "C:\Users\bxvlz\Desktop\autogpt\Auto-GPT\autogpt\llm_utils.py", line 67, in create_chat_completion
    raise RuntimeError("Failed to get response after 5 retries")
RuntimeError: Failed to get response after 5 retries

### Expected behavior 🤔

im pretty sure Auto-GPT should start

### Your prompt 📝

```yaml
ai_goals:
- enter apponents move if hes going 1st and tells you the best move to win
- after moving where the AI tells you to I want it to repeat it after game is ended
- tells you the rating of your oppenet from 1 star to 5 stars
- visual represintation of the chess board
- I want this to work on mobile and on computers
ai_name: Chess-GPT
ai_role: an AI that shows you the next best move for chess

```
