### ISSUE TITLE
Discussion: Streamlining Auto-GPT Configuration with YAML 📝

### ISSUE THREAD

**Issue by lekapsy** [Significant-Gravitas/Auto-GPT#1674]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hi all :)

I have a suggestion that could improve the Auto-GPT project. As we continue to add new configuration options, it's becoming difficult to keep track of everything. So, I thought it might be helpful if we consider switching from using .env files to YAML for our configuration. (keep api keys etc in .env still)

The advantages of using yaml include clearer and more structured configuration, which makes it easier for everyone to understand and maintain the configuration files. Additionally, splitting the configuration into multiple files can help with organization and version control, making maintenance and troubleshooting much easier.

In my opinion, as much as possible should be set in a config.yaml file to make it easier to maintain and modify in the future. There are several places where commands/options/values are hardcoded, making it impossible to "opt" out. To make Auto-GPT more flexible and customizable, we should consider making it easy to change, tweak, and play around with how it interacts with different LLMs in the future.

As I have no real developer experience other that writing scripts as a sysadmin I might be overlooking something obvious or it would be better to just store the configuration with the memory providers that gets loaded on initialization and then changed in a webui etc, but for it's simplicity I think that moving to yaml and standardizing the naming scheme would make a big difference.

However, before I start to make any changes and do an overhaul, I would like to hear everyone's thoughts on the idea and any potential drawbacks Please let me know your opinions so that I can decide if it's a worthwhile improvement.

Thanks!
/Kapsy

### Examples 🌈

An example would be to change how autogpt/prompt.py handles commands, as today there is no option to change this prompt, adding a "enabled" toggle and also load the config from a prompt.yaml or config.yaml would make it easy to just drop one in and change the way it loaded to ignore / build depending on the options in the commands: structure.

```yaml

commands:
  "Google Search":
    name: google
    input: "<search>"
    enabled: false
  "Browse Website":
    name: browse_website
    url: "<url>"
    question: "<what_you_want_to_find_on_website>"
    enabled: false
    
```

When it comes to the main .env file in use now, I see it getting bloated the more external services become available (Local LLM's, TTS / TTI providers etc) where we can easily pull / change settings that is for something general like image generation as a whole, or just for a specific provider.

```yaml
synthesis:
  image:
    general:
      enabled: True
    tti:
      provider:
        openai:
          model: dalle  # Image provider (Example: dalle)
          enabled: true
        huggingface:
          model: sd2nextgen
          enabled: false
  audio:
    general:
      enabled: True
    tts:
      provider:
        local:
          macos: false
          windows: false
        streamelements:
          model: brian
          enabled: false
        elevenlabs:
          model: xyz
          voice:
           id1: 1010102
           id2: 1010101
         enabled: true
```

Or for search something like this:

``` yaml

discovery:
  search:
    general:
      enabled: True
    google:
      CUSTOM_SEARCH_ENGINE_ID: your-custom-search-engine-id  # Custom search engine ID (Example: my-custom-search-engine-id)

         
``` 

### Motivation 🔦

It would be easy to get all data for a specific function that has settings. This is just a quick example:

```python

import yaml

def get_synthesis(yaml_file):
    """
    Given a YAML file with synthesis settings, returns a dictionary with
    information about the enabled image and/or audio synthesis provider(s).
    """
    with open(yaml_file, "r") as f:
        config = yaml.safe_load(f)

    synthesis_data = {}

    if synthesis := config.get("synthesis"):
        image_enabled = synthesis.get("image", {}).get("general", {}).get("enabled", False)
        audio_enabled = synthesis.get("audio", {}).get("general", {}).get("enabled", False)

        if image_enabled:
            providers = synthesis["image"]["tti"]["provider"]
            enabled_providers = [p for p, s in providers.items() if s.get("enabled", False)]
            if len(enabled_providers) != 1:
                raise ValueError("One enabled image provider should be specified")
            image_provider, image_data = enabled_providers[0], providers[enabled_providers[0]]
            synthesis_data["image"] = {"provider": image_provider, "data": image_data}

        if audio_enabled:
            providers = synthesis["audio"]["tts"]["provider"]
            enabled_providers = [p for p, s in providers.items() if s.get("enabled", False)]
            if len(enabled_providers) != 1:
                raise ValueError("One enabled audio provider should be specified")
            audio_provider, audio_data = enabled_providers[0], providers[enabled_providers[0]]
            synthesis_data["audio"] = {"provider": audio_provider, "data": audio_data}

    if len(synthesis_data) > 1:
        providers = list(synthesis_data.keys())
        raise ValueError(f"Only one synthesis section should be enabled. Found {providers}")

    return synthesis_data

```
