### ISSUE TITLE
DevToolsActivePort file doesn't exist when running `browse_website` in WSL2

### ISSUE THREAD

**Issue by clabe45** [Significant-Gravitas/Auto-GPT#1711]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

First off, thanks for devoting your time to this awesome project!

Steps to reproduce:
1. Updated to v0.2.0
2. Type a prompt that triggers the `browse_website` command

I'm running this in WSL2 Fedora. Chromium's installed:

```
$ chromium-browser --version
Chromium 110.0.5481.100 Fedora Project
```

### Current behavior 😯

```
SYSTEM:  Command browse_website returned: Error: Message: unknown error: DevToolsActivePort file doesn't exist Stacktrace: #0 0x5632d3dd8fe3 <unknown> #1 0x5632d3b17d36 <unknown> #2 0x5632d3b44459 <unknown> #3 0x5632d3b40051 <unknown> #4 0x5632d3b3ca9b <unknown> #5 0x5632d3b7eaf7 <unknown> #6 0x5632d3b7e11f <unknown> #7 0x5632d3b75693 <unknown> #8 0x5632d3b4803a <unknown> #9 0x5632d3b4917e <unknown> #10 0x5632d3d9adbd <unknown> #11 0x5632d3d9ec6c <unknown> #12 0x5632d3da84b0 <unknown> #13 0x5632d3d9fd63 <unknown> #14 0x5632d3d72c35 <unknown> #15 0x5632d3dc3138 <unknown> #16 0x5632d3dc32c7 <unknown> #17 0x5632d3dd1093 <unknown> #18 0x7fe98ce6b12d start_thread 
```

### Expected behavior 🤔

The command succeeds

### Your prompt 📝

```yaml
ai_goals:
- Generate a list of names that can be legally used in the us and do not have much
  of an existing web presence
- The names should be short and memorable
ai_name: NameGPT
ai_role: an AI designed to generate a list of name ideas for a tech startup
```
