### ISSUE TITLE
Git clone fails because of strange non-existent paths

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#1734]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

- Ask for any goal that involves Auto-GPT repository

### Current behavior 😯

- Wait for it to attempt cloning to /home/user/autogpt or equivalently absurd path
- See it failing

Example command:

```
NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/autogpt/autogpt', 'clone_path': '/home/user/autogpt'}
```

(note that the repo path is also wrong but it can be made right by various means. This issue is specifically about ChatGPT not knowing what path to use.

### Expected behavior 🤔

Either it knows that it is in an empty filesystem sandbox or the cloning somehow succeeds

### Your prompt 📝

```yaml
ai_goals:
- Google the GitHub repository path of Auto-GPT
- Clone the repository
- Terminate
ai_name: Manager-GPT
ai_role: a project manager in a software company
```
