### ISSUE TITLE
on linux ubuntu, the firefox selenium driver requires a parameter specifying the path to the firefox profile

### ISSUE THREAD

**Issue by p92** [Significant-Gravitas/Auto-GPT#1753]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

export USE_WEB_BROWSER=firefox

then 
python3 -m autogpt --speak --gpt3only 

### Current behavior 😯

on this action :
```
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT', 'question': 'ETHUSDT ticker price'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:Request failed with status code: 401
Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 12 characters remaining, while 32 characters are required for this request.","character_used":10020,"character_limit":10000}}'
```

firefox window popup appear complaining : Your Firefox profile cannot be loaded. It may be missing or inaccessible. 

### Expected behavior 🤔

selenium firefox driver correctly called specifying the profile path (maybe from a new env variable)

### Your prompt 📝

```yaml
# Paste your prompt here
ai_goals:
- find ETH crypto value in USDT
- only use url https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT to retrieve the value
- tell value
- exit
ai_name: eth-usdt
ai_role: crypto trader
```
