### ISSUE TITLE
on linux ubuntu, the chrome selenium driver does not send the correct url to chromium

### ISSUE THREAD

**Issue by p92** [Significant-Gravitas/Auto-GPT#1757]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

export USE_WEB_BROWSER=chrome

then
python3 -m autogpt --speak --gpt3only

### Current behavior 😯

when executing this :+1: 
`Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 12 characters remaining, while 113 characters are required for this request.","character_used":10101,"character_limit":10000}}'
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT', 'question': 'ETH value in USDT'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for ...
Input:Request failed with status code: 401
Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 12 characters remaining, while 32 characters are required for this request.","character_used":10020,"character_limit":10000}}'
y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
`
chromium is started but display an invalid URL :

![image](https://user-images.githubusercontent.com/553530/232260711-7097a615-ed5a-4eec-9e18-869b2fae6d9d.png)

### Expected behavior 🤔

correct url passed to chromium

### Your prompt 📝

```yaml
# Paste your prompt here
ai_goals:
- find ETH crypto value in USDT
- only use url https://api.binance.com/api/v3/ticker/price?symbol=ETHUSDT to retrieve the value
- tell value
- exit
ai_name: eth-usdt
ai_role: crypto trader
```
