### ISSUE TITLE
git clone uses a wrong base dir

### ISSUE THREAD

**Issue by nponeccop** [Significant-Gravitas/Auto-GPT#1971]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [x] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Found another bug with regard to git. 

When it tries to clone to a wrong absolute dir, I provide feedback and tell it that it is in a filesystem sandbox and thus should be using relative paths.

And it uses correctly, using the following:

```
NEXT ACTION:  COMMAND = clone_repository ARGUMENTS = {'repository_url': 'https://github.com/Torantulino/Auto-GPT', 'clone_path': 'Auto-GPT'}
```

Then it tries to read README.md:

```
NEXT ACTION:  COMMAND = read_file ARGUMENTS = {'file': 'Auto-GPT/README.md'}
```

An absolutely sane command, but... the repo was cloned relatively to the process current dir, not relatively to the sandbox dir. So README.md isn't there even though Auto-GPT did everything correctly.

### Current behavior 😯

It cannot read the file

### Expected behavior 🤔

It should be able to read the file.

### Your prompt 📝

```yaml
ai_goals:
- Google something about Auto-GPT
- Write README.md
- Terminate
ai_name: Manager-GPT
ai_role: a project manager in a software company
```
