### ISSUE TITLE
execute_python_file cannot perform write operations

### ISSUE THREAD

**Issue by k-boikov** [Significant-Gravitas/Auto-GPT#2274]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Ask AutoGPT to create any python script that makes changes to the file system.

### Current behavior 😯

![image](https://user-images.githubusercontent.com/64261260/232636269-8e10e590-5e44-4861-9b5b-9d1c0912af17.png)

### Expected behavior 🤔

execute_python_file successfully creates the directory... or maybe we shouldn't allow it?

### Your prompt 📝

```yaml
ai_goals:
- write a python file that creates a new directory named "test" relative to the directory
  of the python file and then execute it in order to create the directory
ai_name: create a new directory
ai_role: write a python file that creates a new directory named "test" relative to
  the directory of the python file and then execute it in order to create the directoryre
```
