### ISSUE TITLE
safe_path_join does not properly join paths

### ISSUE THREAD

**Issue by k-boikov** [Significant-Gravitas/Auto-GPT#2278]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [ ] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

Ask AutoGPT to search for some files in the "/workspace" directory

### Current behavior 😯

Throws error Error: Attempted to access path 'C:\workspace' outside of working directory 'C:\Users\Kris\PycharmProjects\Auto-GPT\auto_gpt_workspace'.
![image](https://user-images.githubusercontent.com/64261260/232637888-07a0bf79-4491-43f8-8d7c-1011a06c5a69.png)

### Expected behavior 🤔

path_in_workspace should always return a path in the workspace

### Your prompt 📝

```yaml
ai_goals:
- try to search files that have the word test in their names
ai_name: search files
ai_role: try to search files that have the word test in their name
```
