### ISSUE TITLE
Docker container needs additional packages

### ISSUE THREAD

**Issue by calevans** [Significant-Gravitas/Auto-GPT#2372]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

- Does not work in master
- Does not work in stable
- 

### Current behavior 😯

```
-  Use the 'execute_shell' command to install pandoc on my system using apt-get, then retry to convert markdown file to html using pandoc.
CRITICISM:  I need to ensure that pandoc is installed successfully before attempting to use it to convert my markdown file to html.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'sudo apt-get install pandoc'}
Executing command 'sudo apt-get install pandoc' in working directory '/home/appuser/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b'/bin/sh: 1: sudo: not found\n'
```

Commands run in the docker container should not need sudo. however, by default, sudo does not exist so none of them ever work.

### Expected behavior 🤔

Commands ether not be run with sudo inside a docker container or sudo be included

### Your prompt 📝

```yaml
ai_goals:
- write a blog post of 200 to 300 words in length praising autoGPT. Save them in markdown format.
ai_name: Opus
ai_role: a blogger who writes about autoGPT
```
