### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket

### ISSUE THREAD

**Issue by emilrueh** [Significant-Gravitas/Auto-GPT#2401]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### GPT-3 or GPT-4

- [X] I am using Auto-GPT with GPT-3 (GPT-3.5)

### Steps to reproduce 🕹

After successfully setting up weaviate with autogpt I keep on getting the error:

### Current behavior 😯

`ResourceWarning: unclosed <ssl.SSLSocket fd=1252, family=2, type=1, proto=0, laddr=('IPA.DRE.S.SX', IPIPI), raddr=('IPA.DR.E.SSX', 443)>`

### Expected behavior 🤔

The error should probably not show.

Wondering whether this can be prevented as it seems rather unsafe.

### Your prompt 📝

```yaml
ai_goals:
- research the most profitable and sucessful trading strategies and learn how to optimize
  them to maximize profitability when used as pine scipts algorithm
- write a pine script version 5 algorithm implementing everything that was learned
  from researching strategies
- backtest and evaluate the algorithm and the trading strategy to make sure it performs
  well and generates high returns in the future
- optimize the algorithm from what was learned during the testing phase
- save the algorithm to a file called auto_trading_v1.pine and let me know once the
  task is completed and shut down
ai_name: Helper
ai_role: an AI designed to write a highly profitable trading bot that works for crypto
  and stocks
```
