### ISSUE TITLE
Is LocalCache working?

### ISSUE THREAD

**Issue by claytondukes** [Significant-Gravitas/Auto-GPT#2450]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

run auto-gpt using local cache

### Current behavior 😯

On first run, it complains that no `AutoGpt.json` exists.

After I create the file and start again, the file remains empty.

### Expected behavior 🤔

I assume AutoGpt.json is used to store the progress so it can continue where it left off? 

Whatever the case, `AutoGpt.json` doesn't seem to get used for anything. A cursory `grep` doesn't show that filename anywhere in the source:

```
$ grep -rIl AutoGpt.json *
$
```

### Your prompt 📝

```yaml
ai_name: Test AI
ai_role: >
  An AI designed to <redacted>
ai_goals:
 # I had to do this to help it remember between restarts, It does work:
  - keep track of your progess in a file, if this is a new session, check the file and continue from where you left off.

# I have yet to get this one to work:
  - first step is to Pre-seed your knowledge of goals by importing the markdown files stored in the docs/ directory, note that if the file is larger than 4KB, it will need to be split into multiple parts before you try to read it.

  - Understand the document located in the docs/ directory and update it to align with your role.
  - do not create empty scripts using "touch", simply create the script with the code when needed, then verify that the file has the code intended.
  - Do not try to install or run programs that require interactive shells such as "nano", or "gedit". Prefer file editing using python, sed, awk, grep, etc.
  - Keep track of any files that you have created. If you try to access a file that you think you created but it is not there, create it.
  - do not to use "execute_shell" to run programs other than for basic needs such as "cd", "mkdir", "sed", "awk", "python", etc. If something absolutely requires using it, log your needs to a file for later review by me and then move on to the next task.
  - Do not try to install missing programs. If a program is missing, log your needs to a file for later review by me and then move on to the next task.
  - Do not attempt to use or run any commands that would require "sudo" when using "execute_shell".
  - Never use ssh.
  - Do not try to make contact with anyone, no emails, no phone calls, no tweets, no posts.
  - do not use clone_repository
 ```

### Your Logs 📒

This is the only relevant "log" (which is not logged, it appears on STDOUT.

```log
Warning: The file 'AutoGpt.json' does not exist. Local memory would not be saved to a file.
```
