### ISSUE TITLE
Define an architecture & support multiple project

### ISSUE THREAD

**Issue by ph-ausseil** [Significant-Gravitas/Auto-GPT#3039]
**EDIT : UPDATE : 26/04 15:10 CET**
* New PR #3316 
* **Definition of 3 levels architecture**

**EDIT : UPDATE : 25/04 18:40 CET**
* Added clarification as #1937 & #3316 are actualy very different

**EDIT : UPDATE : 25/04 13:00 CET**
* New yaml format supported (shown below)
* Code AIConfig & new yaml format to support recursion following @ntindle idea 
* Change not published , I will commit this evening
* Went from 2/11 Task to 4/9 task 

## Idea
**In a 3 layers architecture where you have :**
* **Level 1 :** Management of project / instances
The capacity to create different project with different targets (example build a website, plan a travel, plan a wedding & do my shopping)
* **Level 2 :** Management of team of Agents :
The capacity to operate different agent willing to work on the same project(example build a website)
* **Level 3 :** Agent
The capacity to operate with a AI Model to perform a certain set of task/logical operations.

Discussion : Identify which of these changes must be "core" & which of these change can be supported via plug-ins. 

The PR associated # 3316 cover set first level of architecture & enable the second one.

## Dev Branches
The code should respect the coding conventions I have observed : 
* This branch has memory issues : 
https://github.com/ph-ausseil/Auto-GPT/tree/multiple-config
* This branch makes the choice to break the memory framework: _you will have an exception running it__
https://github.com/ph-ausseil/Auto-GPT/tree/multiple-config-memory
I will focus on LocalCache & maybe Pinecone.

# Proof of Concept/illustrations: 
## This is an example of output : 
<img width="600" alt="Screen Shot 2023-04-23 at 1 27 14 PM" src="https://user-images.githubusercontent.com/303427/233837145-7363135e-c255-4afd-a4fb-df0c4a07ed9c.png">

<img width="600" alt="Screen Shot 2023-04-23 at 7 32 33 PM" src="https://user-images.githubusercontent.com/303427/233855384-b9766818-f943-4e2f-b8f0-d2d136ce6201.png">

<img width="600" alt="Screen Shot 2023-04-23 at 8 09 13 PM" src="https://user-images.githubusercontent.com/303427/233857231-4bc5a2a8-3433-4c9b-a1a2-0efc997d42da.png">

# Plan 

- [x] Get a proof of concept
- [x] Present different  ai_settings.yaml
- [ ] Get green lights
- [ ] Define how much memory should be supported
- [ ] Implement memory compatibility **update : 25/04 workaround found**
- [ ] Implement tests
- [ ] Get support for E2E tests (as GPT-3.5 limit scenarios)

Optional : 
- [x] Split AIConfig in two
-  Implement migration of ai_settings.yaml
-  Implement migration of memories
- [x] Implement support for one of the multiple instances of suggestions

# ai_settings.yaml

## Current file structure 
```yaml
ai_goals:
- 'You will make a detailed summary of each file located in "./python_doc/" as if
  you were an engineer willing to teach another engineer on a new concept. The summary
  must be detailed and contains all subtilities required. Then each summary must be
  saved in a file located in the folder "./python_sumary". '
- Analyze the code in the ./python_doc/ folder and provide suggestions for improvements and optimizations
- Create a list of frequently asked questions (FAQs) related to the content in the ./python_doc/ folder
ai_name: newPythonGPT
ai_role: Produce high-quality and well-detailed documentation and tutorial for Python  Developers
```

## New file structure : 
```yaml
version: X.Y.X
projects : 
 - project : 
   project_name : MyProjectName
   lead_agent :
     agent_goals: 
        - Increase net worth
        - Grow Twitter Account
        - Develop and manage multiple businesses autonomously
      agent_role: an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
      agent_name: Entrepreneur-GPT
      agent_model: A model
   delegated_agents :
    - agent_goals: 
      - There are files located in the folder ./python_doc/ , I want you to go through them and produce a detailed summary aimed at engineers and save these summaries in files located in the folder ./python_summary
      - Analyze the code in the ./python_doc/ folder and provide suggestions for improvements and optimizations
      - Create a list of frequently asked questions (FAQs) related to the content in the ./python_doc/ folder
      agent_name: PythonGPT
      agent_role: Produce high-quality and well-detailed documentation and tutorial for Python Developers 
      agent_model: A model
      agent_model_type: A model type
 - project : 
   project_name : MyOtherProjectName
   lead_agent :
      agent_goals: 
        - Everything non-scrum is bad
        - Let others feel bad
        - Never admit you are wrong
      agent_name: ScrumGPT
      agent_role: Advocate for scrum on Twitter like a 13y/o keyboard warrior 
```

_Originally posted by @ph-ausseil in https://github.com/Significant-Gravitas/Auto-GPT/discussions/922#discussioncomment-5699513_

Also, in order to do my developments, GPT-4 API access would really help if any of you have a contact that may help :). I've been on the waiting list for a very long time :(

**Comment by ph-ausseil** [comment]
Currently not supporting loading a saved PromptGenerator : 
```yaml
- ai_goals:
  - There are files located in the folder ./python_doc/ , I want you to go through
    them and produce a detailed summary aimed at engineers and save these summaries
    in files located in the folder ./python_summary
  - Analyze the code in the ./python_doc/ folder and provide suggestions for improvements
    and optimizations
  - Create a list of frequently asked questions (FAQs) related to the content in the
    ./python_doc/ folder
  ai_name: PythonGPT
  ai_role: Produce high-quality and well-detailed documentation and tutorial for Python
    Developers
  command_registry: null
  prompt_generator: null
- ai_goals:
  - There are files located in the folder ./python_doc/ , I want you to go through
    them and produce a detailed summary aimed at engineers and save these summaries
    in files located in the folder ./python_summary
  - Generate a tutorial for beginners based on the content found in the ./python_doc/
    folder
  - Identify the most important concepts and create a cheat sheet for developers using
    the information in the ./python_doc/ folder
  ai_name: PythonGPT
  ai_role: Produce high-quality and well-detailed documentation and tutorial for Python
    Developers
  command_registry: null
  prompt_generator: null
- ai_goals: A test to see if progress are saved
  ai_name: !!python/tuple
  - Progress are now saved
  ai_role: &id001
  - Look who is older between barrack obama and me
  - check if the earth is flat
  command_registry: ''
  prompt_generator: !!python/object:autogpt.prompts.generator.PromptGenerator
    command_registry: ''
    commands:
    - args: {}
      function: null
      label: Do Nothing
      name: do_nothing
    - args:
        reason: <reason>
      function: null
      label: Task Complete (Shutdown)
      name: task_complete
    constraints:
    - ~4000 word limit for short term memory. Your short term memory is short, so
      immediately save important information to files.
    - If you are unsure how you previously did something or want to recall past events,
      thinking about similar events will help you remember.
    - No user assistance
    - Exclusively use the commands listed in double quotes e.g. "command name"
    goals: *id001
    name: Progress are now saved
    performance_evaluation:
    - Continuously review and analyze your actions to ensure you are performing to
      the best of your abilities.
    - Constructively self-criticize your big-picture behavior constantly.
    - Reflect on past decisions and strategies to refine your approach.
    - Every command has a cost, so be smart and efficient. Aim to complete tasks in
      the least number of steps.
    - Write all code to a file.
    resources:
    - Internet access for searches and information gathering.
    - Long Term memory management.
    - GPT-3.5 powered Agents for delegation of simple tasks.
    - File output.
    response_format:
      command:
        args:
          arg name: value
        name: command name
      thoughts:
        criticism: constructive self-criticism
        plan: '- short bulleted
          - list that conveys
          - long-term plan'
        reasoning: reasoning
        speak: thoughts summary to say to user
        text: thought
    role: A test to see if progress are saved
```

**Comment by ph-ausseil** [comment]
<img width="933" alt="Screen Shot 2023-04-23 at 7 32 33 PM" src="https://user-images.githubusercontent.com/303427/233855384-b9766818-f943-4e2f-b8f0-d2d136ce6201.png">

Status : Encountering issues related to LLM but test are ok :-) , probably need to set a "version" to the ai_settings.yaml to manage backward-compatibility

if the version doesn't exist
execute transform_config_v0_to_VX
if the version is between VY  and  VX 
execute transform_config_VY_to_VX

**Comment by ido777** [comment]
> Can I split AIConfig in two, not required for functionality but for modularity and clarty of the code.
** AIConfigList / AIConfigLoader (that contains a list of AIConfig)
** AIConfig

IMO, it is required for functionality. 
From my perspective, this is one of the most important changes from the original design.
Currently, the autoGPT has 2 "internal models" FAST_LLM, and SMART_LLM, and the PROMPT comes partly from code and partly from the user (in different forms)

In order to design multiple different bots from different models (and probably working on different goals) talking with each other it will help if we will 
1) differentiate between different **possible** configurations (e.g. different system_promt (what you called prompt_generator) for different models, or even for different testing. what you called AIConfigList / AIConfigLoader
2) differentiate between different **actual** configurations, for multiple copies of the same configuration (e.g. to avoid duplicating of the same goal such as PythonGPT & PythonGPT2. 
3) move the current connection between autoGPT internal logic and prompt generation so all the adaptions to different models won't hide in the code. moreover, it will ease testing and development

**Comment by ph-ausseil** [comment]
> ###
> [Apr 24, 2023](#issuecomment-1519535982)

It is not required, as show the screenshot the POC is working and the only issue at the moment is memory loss. But It would be none the less very easy to set & interesting. At this stage I am waiting for contributor feedbacks.

> : How do you envision controlling PythonGPT & PythonGPT2, from duplicating efforts? (It seems their definition should be to do what the third agent will ask them)

This is out of scope. **Multiple-instance suggestion 1 ** & **Multiple-instance suggestion 2 ** may set the foundation for such functionality. If you want to have multiple instance you can implement it many way , but one of them is to upgrade ai_settings.yaml management.

**Comment by iller75** [comment]
This is kind of exactly what i suggested a day or two ago, awesome work :D

**Comment by ph-ausseil** [comment]
Hey, Is it possible to have any thoughs from the team @k-boikov @ntindle @Pwuts @Torantulino @BillSchumacher , I'm getting a real workload managing conflicts 😅

**Comment by ntindle** [comment]
> # Status :
> Encountering issues related to LLM, but tests are ok, except for the issues below.
> 
> # Major Issue :
> * As it is, memory seems broken
> * Need team feedback/green lights
> 
> # Minor issue :
> ## Migration of ai_settings.yaml
> The existing yaml will not be backward compatible as is; it can be fixed :
> 
> ```
> if the versions don't exist
> execute transform_config_v0_to_VX()
> if the version is between VY  and  VX 
> execute transform_config_VY_to_VX()
> ```
> 
> ## Migration of Cache
> The existing memory will not be backward compatible as is; it can be fixed :
> 
> ```
> if the versions don't exist
> execute transform_cache_v0_to_VX()
> if the version is between VY  and  VX 
> execute transform_cache_VY_to_VX()
> ```
> 
> ## GPT-4 E2E test
> I many of my test scenarios can’t go End-to-End because I do not have GPT-4 API.
> 
> # Discussions :
> * **Is it wanted ?**
>   if wanted, can this be re-used for multiple instances? (I can work on it…)
>   do we need retro compatibility on yaml & cache, or is it acceptable at this stage?
>   if yes, do we need it on all cache systems? Or does the suggested functionality outweigh the requirement of having X+ cache solutions?  (define X 😊)
> * **Can I split AIConfig in two?** Not required for functionality but for modularity and clarity of the code.
>   AIConfigList / AIConfigLoader (that contains a list of AIConfig)
>   AIConfig
> * **Multiple-instance suggestions 1 & 2 show a need for planning**
>   The model needs to be defined today; it is though as two options slow/fast because it is though for LLM
>   How to implement models that are not LLM (car plate recognition, image generation, plant strain recognition, Coding expertise, Mathematic expertise, etc...)
> 
> # Lesson Learned :
> **Supporting too many memories as core functions (and not plug-ins) at this stage of the development of AutoGPT (before multiple instances, multiple configs, multiple LLM support...) of the software is not a good idea** 😢

Dont migrate the files, backwards compatibility hasn't been considered until now, and I don't plan to start

**Comment by ntindle** [comment]
> Multiple-instance suggestion 1:
> add: projects
> add: projects > project
> add: projects > project > lead_ai_name
> add: projects > project > ai
> add: projects > project > ai > model

> Multiple-instance suggestion 2:
> add: projects
> add: projects > project
> add : projects > project > lead_ai
> add : projects > project > delegated_ai
> add: projects > project > delegated_ai > model


Have we considered a `goal > objective > leader` architecture?

We start with 

```yaml
goal: Make more paperclips
Leader: 
 - model: GPT4
   name: THE PAPERCLIPPER
   objectives:
     - goal: Gather Materials
        leader: 
        - model: GPT3.5
          name: the miner
          objectives:
          - mine
      - goal: Build Factories
        leader:
        - model: GPT4
           name: Factory Construction Supervisor
           objectives: 
           - goal: Design Factory
             leader: GPT4
             objectives:
               - goal: Generate an image of a factory
                  leader: HF
           - goal: Get factory materials
             leader: GPT3.5
             . . .
           - goal: combine materials
            . . .
           - goal: finish factory
          . . . 
   ```
