### ISSUE TITLE
allow `ai_name`, `ai_role` and `ai_goals` as cli args

### ISSUE THREAD

**Issue by nalbion** [Significant-Gravitas/Auto-GPT#3079]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently the only way of starting Auto-GPT unattended is with `--continuous --ai-settings ai_settings.xml` but it would also be good if you could instead/additionally provide any/all of the 3 fields to the cli:

-ai_name
-ai_role
-ai_goals

### Motivation 🔦

I have been using Auto-GPT to create a Github action that will invoke Auto-GPT: https://github.com/nalbion/auto-gpt-action

Ideally I'd be able to use something like:

```yaml
runs:
  using: docker
  image: significantgravitas/auto-gpt
  env:
    OPENAI_API_KEY: ${{ inputs.openai_key }}
  args:
    - --ai_name ${{ inputs.ai_name }}
    - --ai_role ${{ inputs.ai_role }}
    - --ai_goals ${{ inputs.issue_body }}
```

but because the only way of providing these properties is via the `--ai-settings` cli argument, I need to create an `ai_settings.yaml` file before running the container with the default ENTRYPOINT `python -m autogpt`.

There may be other ways of working around this, I tried suggesting to Auto-GPT to:
- split the action into a Composite which also runs a local Docker action, or
- `runs.pre-entrypoint: generate-ai-settings.py`

...but it insisted on creating a new Docker image just so that it could run `generate-ai-settings.py` from there.
