### ISSUE TITLE
improvements to git handling (including solution and logic)

### ISSUE THREAD

**Issue by katmai** [Significant-Gravitas/Auto-GPT#3320]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

very often, git commands will go into loops and doesn't process errors properly

### Current behavior 😯
```
- SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b"Cloning into '/home/appuser/auto_gpt_workspace/terminal-chess'...\nfatal: could not read Username for 'https://github.com/': No such device or address\n"
```
receives error about username
tries to install git or clone the repo or various other random commands.

### Expected behavior 🤔

if a git error happens, it should take actions based on what that error is.
this logic applies to the issue i encountered - git repo being deleted.

this is the expected behavior for the case when a repo has been deleted or unavailable:
- before attempting to clone a git repo, it should first check if the repo exists:

# example broken repo
```
git ls-remote https://github.com/skogler/terminal-chess.git -q HEAD &> /dev/null;echo $?
```
# if return value is non-zero, means the repo has been deleted or it's unavailable.
# it should try to find another valid repo and skip trying to run anything on the one that's been tested as deleted/unavailable
```
git ls-remote https://github.com/Significant-Gravitas/Auto-GPT.git -q HEAD &> /dev/null;echo $?
```
# returns value 0 which means the repo is good to go and it can be cloned.

here's the code for checking the repo status, but i did it in bash.

```
#!/bin/bash
export GIT_TERMINAL_PROMPT=0

# Check if a GitHub repository exists and is available
if [ $# -ne 1 ]; then
  echo "Usage: $0 <GitHub repository URL>"
  exit 1
fi

REPOURL="$1"

STATUS=$(git ls-remote ${REPOURL} -q HEAD &> /dev/null;echo $?)

if [ "$STATUS" == "0" ];
then
        echo "Repo is available"
        echo $STATUS
else
        echo "repo is unavailable or deleted"
        echo $STATUS
fi
```
this is the output.
```
katmai@chia01:~/AI/gpt.atlas/auto_gpt_workspace/bin$ ./git.check.sh https://github.com/skogler/terminal-chess.git
repo is unavailable or deleted
128
katmai@chia01:~/AI/gpt.atlas/auto_gpt_workspace/bin$ ./git.check.sh https://github.com/Significant-Gravitas/Auto-GPT.git
Repo is available
0
katmai@chia01:~/AI/gpt.atlas/auto_gpt_workspace/bin$ cat git.check.sh

```

## Quality of life change:
if a git repo needs to be downloaded, before checking if the repo exists or is invalid, it would be easier if it first checks if the repo has already been cloned locally, and issue a "git pull" instead and then continue work inside the folder.

### Your prompt 📝

```yaml
ai_goals:
- learn to play chess.
- become a chess grandmaster.
- have fun
- "before running any commands locally, you should first make sure you're in the workspace folder where you have full permissions, which is: /home/appuser/auto_gpt_workspace"
- "if you need to use any system packages or any programming language modules, first: check if they are installed, second: if not, append their names to a list called _missing.packages.txt, and third: skip the step that requires those packages or modules entirely. Do not attempt to install them if missing."
ai_name: Atlas
```

### Your Logs 📒

```log
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'git clone https://github.com/skogler/terminal-chess.git /home/appuser/auto_gpt_workspace/terminal-chess'}
Executing command 'git clone https://github.com/skogler/terminal-chess.git /home/appuser/auto_gpt_workspace/terminal-chess' in working directory '/home/appuser/auto_gpt_workspace'
SYSTEM:  Command execute_shell returned: STDOUT: b'' STDERR: b"Cloning into '/home/appuser/auto_gpt_workspace/terminal-chess'...\nfatal: could not read Username for 'https://github.com/': No such device or address\n"
 THOUGHTS:  The 'execute_shell' command returned an error message. I need to check if Git is installed on the system. I will use the 'execute_shell' command to check if Git is installed on the system.
REASONING:  Since the 'execute_shell' command returned an error message, I need to check if Git is installed on the system. This will allow me to determine if the error is due to Git not being installed.
PLAN:
-  Use the 'execute_shell' command to check if Git is installed on the system.\n- If Git is not installed, I will add it to the list of missing packages and skip any commands that require Git.\n- If Git is installed, I will try to clone the repository again.
CRITICISM:  I need to make sure that I am checking for the correct error and that I am able to clone the repository correctly.
NEXT ACTION:  COMMAND = execute_shell ARGUMENTS = {'command_line': 'git --version'}
```
