### ISSUE TITLE
Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found

### ISSUE THREAD

**Issue by Molnfront** [Significant-Gravitas/Auto-GPT#3403]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

There is no tag in the command for pulling the image from docker hub, in the setup instructions.

It should be **docker pull significantgravitas/auto-gpt:0.2.2** not **docker pull significantgravitas/auto-gpt**

### Current behavior 😯

Using default tag: latest
Error response from daemon: manifest for significantgravitas/auto-gpt:latest not found: manifest unknown: manifest unknown

### Expected behavior 🤔

It will install the image.

**Comment by ScotTFO** [comment]
For now this worked for me:
docker pull significantgravitas/auto-gpt:0.2.2

It's not finding "latest" because it's named the release version on dockerhub:
https://hub.docker.com/r/significantgravitas/auto-gpt/tags

**Comment by Pwuts** [comment]
You're right, this currently is broken. It should be fixed after the next release:
https://github.com/Significant-Gravitas/Auto-GPT/blob/7a161cc0bd8253759c8e7b15c0a3e3d86f0adbad/.github/workflows/docker-release.yml#L47-L50

**Comment by Besix2** [comment]
In the meantime just use docker pull significantgravitas/auto-gpt:0.2.2 to pull the image

**Comment by stneric** [comment]
I have the same issue. Yes, you can pull it with significantgravitas/auto-gpt:0.2.2 but you can't run it via docker-compose run --rm auto-gpt. To run it in its current configuration, edit your docker-compose.yaml and in line 4 add ":0.2.2" to the "image: signi...-gpt". It should look like this:

image: significantgravitas/auto-gpt:0.2.2

Now try running it again (in terminal, docker-compose run --rm auto-gpt)

Hope this helps :)

**Comment by jabowery** [comment]
> ...To run it in its current configuration, edit your docker-compose.yaml and in line 4 add ":0.2.2" 

There is no such line 4:

```
# To boot the app run the following:
# docker-compose run auto-gpt
version: "3.9"

services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"
```

**Comment by stneric** [comment]
I see. Change your .yaml to the following:

```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt:0.2.2
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
  redis:
    image: "redis/redis-stack-server:latest"
```
    
    
    I hope the formatting is ok. .yaml is a bit tricky but I will gladly help however I can. 
    Let me know if that fixed it :)
