### ISSUE TITLE
Failed to connect to Redis

### ISSUE THREAD

**Issue by Xerizaf** [Significant-Gravitas/Auto-GPT#3476]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Connect to Redis

### Current behavior 😯

FAILED TO CONNECT TO REDIS  Error 99 connecting to localhost:6379. Cannot assign requested address.
DOUBLE CHECK CONFIGURATION  Please ensure you have setup and configured Redis properly for use. You can check out https://github.com/Torantulino/Auto-GPT#redis-setup to ensure you've set up everything correctly.

### Expected behavior 🤔

To connect properly

### Your prompt 📝

```yaml
# Paste your prompt here
```

### Your Logs 📒

```log
<insert your logs here>
```

**Comment by zweite** [comment]
```
version: "3.9"
services:
  auto-gpt:
    depends_on:
      - redis
    build: ./
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: redis
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
    links:
      - redis
  redis:
    image: "redis/redis-stack-server:latest"
    restart: always
    ports:
      - '6379:6379'
```
