### ISSUE TITLE
Scraping Websites - Token limit issue still occurring with latest commit

### ISSUE THREAD

**Issue by remriel** [Significant-Gravitas/Auto-GPT#3637]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Latest release

I gave it my Reddit API keys and asked to scrape the top posts in /r/Midjourney

First it tried to clone it as a repository, then got stuck in a loop trying to figure out the URL, and keep receiving "Error:" after Criticism with no error message

SYSTEM:  Command clone_repository returned: Error: Cmd('git') failed due to: exit code(128) cmdline: git clone -v -- https://*****:*****@www.reddit.com/r/midjourney/ /home/RedditScraperGPT/Midjourney stderr: 'Cloning into '/home/RedditScraperGPT/Midjourney'... fatal: repository 'https://www.reddit.com/r/midjourney/' not found '

Edit: Above is resolved. Now hitting token limit again

### Your prompt 📝

```yaml
ai_goals:
- Utilize web scraping techniques to extract comments from the top posts in /r/Midjourney on Reddit http://reddit.com/r/midjourney
- Save the output to a text file in a structured and organized format for easy analysis and further processing.
- Continuously monitor the subreddit for new top posts and update the output file accordingly.
- Create a web interface for navigating and changing options for scraping.
- REDDIT_CLIENT_ID=
- REDDIT_CLIENT_SECRET=
- REDDIT_USER_AGENT=
ai_name: RedditScraperGPT
ai_role: coding a web app for scraping posts from /r/Midjourney on Reddit
api_budget: 0.0

```

### Your Logs 📒

https://gist.githubusercontent.com/remriel/ea20ffcdc1afeb9876fe1c7d7bc7458d/raw/f7dd1a269aa12e85fbf3a3997b247d529ca3f369/errorlog.log
