### ISSUE TITLE
Not aware of past command+arguments; often enters "forever loops" and repeats the same actions

### ISSUE THREAD

**Issue by DanielNeedles** [Significant-Gravitas/Auto-GPT#3644]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

There are multiple examples of this.  In this case, it tries to clone the auto-GPT repo twice in a row.  If it was aware of it's previous command(s), it would know to skip that.

AI Name: Update-Auto-GPT-With-LangChain
Describe your AI's role:  Update-Auto-GPT-With-LangChain is: an AI adept at Python and other programming languages and modules for the purpose of improving Auto-GPT
Goal 1: Clone auto-gpt so you can make updates to it.
Goal 2: Identify where OpenAI is called and replace it with the appropriate LangChain calls
Goal 3: Expand the commandline arguments to include an argument for chosing which AI the caller wants to use
Goal 4: Update the help and usage messages to include this new parameter
Goal 5: Make the commandline argument for chosing which AI the caller wants to use optional.  Default OpenAI as the AI used.

### Current behavior 😯

It doesn't track what it has already done and often will repeat the same commands with the same arguments leading to redundancy as well as "time loops" where it loops through the same series of steps forever and never tries anything else.

### Expected behavior 🤔

It should either locally remember or add to the prompt the past steps and either try something different or quit gracefully if it cannot think of anything different to do.

### Your prompt 📝

```yaml
ai_goals:
- Clone auto-gpt so you can make updates to it.
- Identify where OpenAI is called and replace it with the appropriate LangChain calls
- Expand the commandline arguments to include an argument for chosing which AI the
  caller wants to use
- Update the help and usage messages to include this new parameter
- Make the commandline argument for chosing which AI the caller wants to use optional.  Default
  OpenAI as the AI used.
ai_name: Update-Auto-GPT-With-LangChain
ai_role: an AI adept at Python and other programming languages and modules for the
  purpose of improving Auto-GPT
```

### Your Logs 📒

```
log
(venv) D:\WORK\CLOUD\AUTO-GPT-GR\logs>grep  -E "^        |DEBUG  System.*exit code" activity.log | grep -E -v "text.:|reasoning.:|plan.:|criticism.:|speak.:"
        "name": "command name",
        "args": {
            "arg name": "value"
        }
        "name": "clone_repository",
        "args": {
            "repository_url": "https://github.com/openai/gpt-3",
            "clone_path": "C:\\Users\\Dad\\My Drive\\WORK\\CLOUD\\AUTO-GPT-GR\\auto_gpt_workspace\\auto-gpt"
        }
        "name": "clone_repository",
        "args": {
            "repository_url": "https://github.com/openai/gpt-3",
            "clone_path": "C:\\Users\\Dad\\My Drive\\WORK\\CLOUD\\AUTO-GPT-GR\\auto_gpt_workspace\\auto-gpt"
        }
        "name": "command name",
        "args": {
            "arg name": "value"
        }
        "name": "search_files",
        "args": {
            "directory": "C:\\Users\\Dad\\My Drive\\WORK\\CLOUD\\AUTO-GPT-GR\\auto_gpt_workspace\\auto-gpt",
            "search_term": "OpenAI"
        }
        "name": "command name",
        "args": {
            "arg name": "value"
        }
        "name": "search_files",
        "args": {
            "directory": "C:\\\\Users\\\\Dad\\\\My Drive\\\\WORK\\\\CLOUD\\\\AUTO-GPT-GR\\\\auto_gpt_workspace\\\\auto-gpt",
            "search_term": "def generate_text("
        }
        "name": "command name",
        "args": {
            "arg name": "value"
        }
        "name": "clone_repository",
        "args": {
            "repository_url": "https://github.com/openai/gpt-3",
            "clone_path": "C:\\Users\\Dad\\My Drive\\WORK\\CLOUD\\AUTO-GPT-GR\\auto_gpt_workspace\\auto-gpt"
        }
2023-05-01 14:09:59,051 DEBUG  System: Command clone_repository returned: Error: Cmd('git') failed due to: exit code(128)
        "name": "command name",
        "args": {
            "arg name": "value"
        }
        "name": "search_files",
        "args": {
            "directory": "C:\\Users\\Dad\\My Drive\\WORK\\CLOUD\\AUTO-GPT-GR\\auto_gpt_workspace\\auto-gpt",
            "search_term": "def generate_text("
        }
```
