### ISSUE TITLE
filename for the write command in the arguments is correct, but error seems to indicate it is using another filename (txt vs jpg)

### ISSUE THREAD

**Issue by oneindelijk** [Significant-Gravitas/Auto-GPT#3743]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

1. Ask autogpt to do some research and write the results to a file

### Current behavior 😯

autogpt specifies command 'write_to_file' and correct .txt file as argument.
command returns error about a different .jpg file
autogpt feels quilty and wants to try again, with the same outcome

### Expected behavior 🤔

The command should be executed with the given arguments: it should write to the textfile in the argument instead of a jpg file that is nowhere mentioned

### Your prompt 📝

```yaml
ai_goals:
- Analyze the information and data provided by https://www.tesla-intergalactic.org/bluebus
  to identify potential fundraising opportunities and target audiences.
- Learn more about the mission, organization, values from the .txt files in the working directory
- Develop and implement a comprehensive fundraising plan that includes various methods
  such as online campaigns, events, sponsorships, and grants.
- Engage volunteers to help grow the community, improve the website, work and live on the bus, create and manage social media content and more
- Build and maintain relationships with donors and supporters to ensure long-term
  engagement and continued support.
- Monitor and evaluate the effectiveness of fundraising strategies, making adjustments
  as necessary to maximize results.
- Provide regular updates and reports on fundraising progress and future plans to
  keep the organization informed and engaged.
ai_name: FIPGPT
ai_role: a versatile autonomous agent designed to assist organizations in increasing
  their funding by providing effective and innovative fundraising strategies.
api_budget: 0.0

```

### Your Logs 📒

```log
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'filename': '/home/sam/AUTOGPT/autogpt/auto_gpt_workspace/fundraising_recommendations.txt', 'text': "Here are the recommendations to recruit and engage volunteers for the Blue Bus Community that align with the organization's goals: \n- Utilize social media platforms.\n- Host volunteer recruitment events.\n- Reach out to local schools and universities.\n- Partner with community organizations.\n- Provide impactful volunteer experiences.\n- Develop a recognition program.\n- Foster a welcoming and supportive environment."}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command write_to_file returned: Error: '/home/sam/AUTOGPT/autogpt/auto_gpt_workspace/98de3af5-0079-40a7-b364-cd33643b9e15.jpg'
 THOUGHTS:  I received an error message. It seems that there was a mistake in the arguments I provided for the 'write_to_file' command, resulting in the command trying to create an image file instead of a text file. I will use the correct arguments and retry the 'write_to_file' command.
REASONING:  Mistakes with commands are common, but it's important to analyze the error message to find out what went wrong and reattempt the command with the correct arguments.
PLAN: 
-  Correct the argument error and use the 'write_to_file' command to save the fundraising recommendations in a text file so that they can be used for future reference.
CRITICISM:  The mistake is due to my carelessness in specifying the filename argument.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'filename': '/home/sam/AUTOGPT/autogpt/auto_gpt_workspace/fundraising_recommendations.txt', 'text': "Here are the recommendations to recruit and engage volunteers for the Blue Bus Community that align with the organization's goals: \n- Utilize social media platforms.\n- Host volunteer recruitment events.\n- Reach out to local schools and universities.\n- Partner with community organizations.\n- Provide impactful volunteer experiences.\n- Develop a recognition program.\n- Foster a welcoming and supportive environment."}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 's' to run self-feedback commands'n' to exit program, or enter feedback for ...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command write_to_file returned: Error: '/home/sam/AUTOGPT/autogpt/auto_gpt_workspace/98de3af5-0079-40a7-b364-cd33643b9e15.jpg'

```
