### ISSUE TITLE
Gateway Error shutsdown the whole application

### ISSUE THREAD

**Issue by eleijonmarck** [Significant-Gravitas/Auto-GPT#381]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I turned it on in continous mode for y -100 and then i came back with the following error:

### Current behavior 😯

openai.error.APIError: Gateway timeout. {"error":{"code":524,"message":"Gateway timeout.","param":null,"type":"cf_gateway_timeout"}} 524 {'error': {'code': 524, 'message': 'Gateway timeout.', 'param': None, 'type': 'cf_gateway_timeout'}} {'Date': 'Fri, 07 Apr 2023 10:04:55 GMT', 'Content-Type': 'application/json', 'Content-Length': '92', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '7b41645cab505d3b-LIS'}

### Expected behavior 🤔

not to crash but get back to the state it was

### Your prompt 📝

```yaml
Continue with the last settings?
Name:  blogger
Role:  ai
Goals: ['improve my blog https://eleijonmarck.dev/']
Continue (y/n): y
Using memory of type: PineconeMemory
```
