### ISSUE TITLE
Command google_search never invoked anymore

### ISSUE THREAD

**Issue by jaykayenn** [Significant-Gravitas/Auto-GPT#3904]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

Start a goal that's primarily searching the web

### Current behavior 😯

Instead of searching Google or any other search engine, it will always 'browse website' instead. Even when the declared plan is to use search engines. Browsing the homepage of search engines and archive sites obviously yield no results. 

### Expected behavior 🤔

Use 'google_search' command like it used to before the latest release. 

### Your prompt 📝

```yaml
# Search and summarize recent articles on the topic of XXX
```

**Comment by jaykayenn** [comment]
Google API and custom search ID already set in .env. No errors or warnings thrown.

**Comment by k-boikov** [comment]
Try prompting explicitly to use the google_search command.

**Comment by z-x-x136** [comment]
> 尝试明确提示使用 google_search 命令。

What do you mean? Can you give me an example

Thank

**Comment by jaykayenn** [comment]
> Try prompting explicitly to use the google_search command.

I have, and it seems to understand. Yet, the generated command is 'browse_website' instead of 'google_search'. It just keeps scraping google com homepage.

**Comment by gsibert** [comment]
I believe command changed to just google but it returns disabled for me.

**Comment by yangkyeongmo** [comment]
I'm having the same issue. AutoGPT agent is ran by this command:
`docker compose run --build --rm auto-gpt`
Where docker-compose.yaml looks like this:
```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt:0.2.2
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      - ./ai_settings.yaml:/app/ai_settings.yaml
  redis:
    image: "redis/redis-stack-server:latest"
```
which is same with document.

From this environment, I found DEBUG message says it's allowed with commands without "google_search" nor "google" in it:
`
Commands:\n1. analyze_code: Analyze Code, args: \"code\": \"<full_code_string>\"\n2. read_audio_from_file: Convert Audio to text, args: \"filename\": \"<filename>\"\n3. execute_python_file: Execute Python File, args: \"filename\": \"<filename>\"\n4. execute_shell: Execute Shell Command, non-interactive commands only, args: \"command_line\": \"<command_line>\"\n5. execute_shell_popen: Execute Shell Command, non-interactive commands only, args: \"command_line\": \"<command_line>\"\n6. append_to_file: Append to file, args: \"filename\": \"<filename>\", \"text\": \"<text>\"\n7. delete_file: Delete file, args: \"filename\": \"<filename>\"\n8. list_files: List Files in Directory, args: \"directory\": \"<directory>\"\n9. read_file: Read file, args: \"filename\": \"<filename>\"\n10. write_to_file: Write to file, args: \"filename\": \"<filename>\", \"text\": \"<text>\"\n11. clone_repository: Clone Repository, args: \"url\": \"<repository_url>\", \"clone_path\": \"<clone_path>\"\n12. generate_image: Generate Image, args: \"prompt\": \"<prompt>\"\n13. improve_code: Get Improved Code, args: \"suggestions\": \"<list_of_suggestions>\", \"code\": \"<full_code_string>\"\n14. send_tweet: Send Tweet, args: \"tweet_text\": \"<tweet_text>\"\n15. browse_website: Browse Website, args: \"url\": \"<url>\", \"question\": \"<what_you_want_to_find_on_website>\"\n16. write_tests: Write Tests, args: \"code\": \"<full_code_string>\", \"focus\": \"<list_of_focus_areas>\"\n17. delete_agent: Delete GPT Agent, args: \"key\": \"<key>\"\n18. get_hyperlinks: Get text summary, args: \"url\": \"<url>\"\n19. get_text_summary: Get text summary, args: \"url\": \"<url>\", \"question\": \"<question>\"\n20. list_agents: List GPT Agents, args: () -> str\n21. message_agent: Message GPT Agent, args: \"key\": \"<key>\", \"message\": \"<message>\"\n22. start_agent: Start GPT Agent, args: \"name\": \"<name>\", \"task\": \"<short_task_desc>\", \"prompt\": \"<prompt>\"\n23. Task Complete (Shutdown): \"task_complete\", args: \"reason\": \"<reason>\"\n\n
`
Sorry that it's hard to read. But this commands list does not contain "google" nor original "google_search" in it. I get original "google_search" is changed to "google" but for now it does not seem to be included in default docker image.
