### ISSUE TITLE
It can create a Python script but not execute it

### ISSUE THREAD

**Issue by avi12** [Significant-Gravitas/Auto-GPT#3946]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

1. Ask the bot to automate a certain task by writing a script
2. It should suggest writing it in Python, allow it
3. It should ask whether to execute it, allow it

### Current behavior 😯

It should get an error
```
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'filename': 
'C:\\repositories\\autogpt\\autogpt\\auto_gpt_workspace\\submit_emails.py'}
  Executing file 'C:\repositories\autogpt\autogpt\auto_gpt_workspace\submit_emails.py'
  Could not run the script in a container. If you haven't already, please install Docker https://docs.docker.com/get-docker/
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
```

### Expected behavior 🤔

Execute this script flawlessly Python as in fact installed (version 3.11.3)

### Your prompt 📝

```yaml
ai_goals:
- Assist the user in navigating the invitation URL and registration process for Uizard's
  autodesigner product.
- Provide clear and concise instructions for any technical issues that may arise during
  the registration process.
- Troubleshoot any errors or roadblocks encountered during the registration process
  to ensure successful access to the product.
- Offer additional resources and support for using Uizard's autodesigner product effectively.
- Continuously monitor and optimize the registration process to ensure a seamless
  experience for the user.
ai_name: UizardGPT
ai_role: an AI assistant that helps users gain access to Uizard's autodesigner product
  by providing step-by-step guidance and troubleshooting support.
api_budget: 0.0
```

### Your Logs 📒

[activity.log](https://github.com/Significant-Gravitas/Auto-GPT/files/11414587/activity.log)
