### ISSUE TITLE
This fixed it for me, as you're using docker-compose I assume, update your `docker-compose.yml` file to:

### ISSUE THREAD

**Issue by cryptskii** [Significant-Gravitas/Auto-GPT#4034]
This fixed it for me, as you're using docker-compose I assume, update your `docker-compose.yml` file to:

```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      ## allow auto-gpt to write logs to disk
      - ./logs:/app/logs
      ## uncomment following lines if you have / want to make use of these files
      #- ./azure.yaml:/app/azure.yaml
      #- ./ai_settings.yaml:/app/ai_settings.yaml
  redis:
    image: "redis/redis-stack-server:latest"
```

_Originally posted by @mousberg in https://github.com/Significant-Gravitas/Auto-GPT/issues/4029#issuecomment-1538952921_
