### ISSUE TITLE
CI pipeline cache dependencies

### ISSUE THREAD

**Issue by merwanehamadi** [Significant-Gravitas/Auto-GPT#4258]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Cache dependencies in ci pipeline: 

```
- name: Cache pip
  uses: actions/cache@v2
  with:
    path: ~/.cache/pip
    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    restore-keys: |
      ${{ runner.os }}-pip-

- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
```
can really matter once people run challenges, an immediate feedback loop to see challenge results can really improve user experience.
