### ISSUE TITLE
Formatting of Goals 

### ISSUE THREAD

**Issue by WKimandu** [Significant-Gravitas/Auto-GPT#4263]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Master (branch)

### GPT-3 or GPT-4?

GPT-3.5

### Steps to reproduce 🕹

I am running 0.3.1 
When i provide my instructions the goals derives are a series of characters
WARNING:  You are running on `master` branch - this is not a supported branch.
WARNING: SystemInformationPlugin: EXECUTE_LOCAL_COMMANDS is false. System information will not be added to the context.

Plugins found: 9
--------------------
  Auto-GPT-Dolly-Plugin: 0.2.0 - This plugin adds a clone_autogpt command that lets Auto-GPT build an army of powerful minions.
  Auto-GPT-Dolly-Plugin: 0.2.0 - This plugin adds a clone_autogpt command that lets Auto-GPT build an army of powerful minions.
  autogpt-api-tools: 0.1.0 - Allow AutoGPT to make API calls to outside services.
  Auto-GPT-Space-Plugin: 0.1.3 - Auto-GPT Space Plugin: Get the number of astronauts in space in real-time..
  autogpt-random-values: 0.1.0 - Enable Auto-GPT with the power of random values.
  autogpt-wikipedia-search: 0.1.0 - Wikipedia search integrations.
  Auto-GPT-Plugin-SystemInfo: 0.1.2 - This is system info plugin for Auto-GPT.
  Auto-GPT-User-Input: 0.1.0 - This is a plugin which simply allows AutoGPT to specifically request user input
  Auto-Web-Interaction-Plugin: 0.1.0 - Auto-GPT Web Interaction Plugin: Interact with websites.
Welcome back!  Would you like me to return to being AI Web Guru?
  Asking user via keyboard...
Continue with the last settings?
Name:  AI Web Guru
Role:  Write a blog article that outlines the features for Bs4, requests, and selenium to scrape or reverse engineer websites. Give use cases when each is the preferred tool, when to combine them, and how to achieve specific goals. Provide when each is typically used other use case is reverse engineer websites and other times it is to parse articles and save them when they are relevant to my research. Other use cases include scraping data from websites to create datasets for machine learning models, and another use case is to create screenshots of web UI configurations for documentation purposes.
Goals: ['A', 's', ' ', 'a', 'n', ' ', 'A', 'I', ' ', 'w', 'e', 'b', ' ', 'g', 'u', 'r', 'u', ',', ' ', 'y', 'o', 'u', ' ', 'w', 'a', 'n', 't', ' ', 't', 'o', ' ', 'w', 'r', 'i', 't', 'e', ' ', 'a', ' ', 'b', 'l', 'o', 'g', ' ', 'a', 'r', 't', 'i', 'c', 'l', 'e', ' ', 't', 'h', 'a', 't', ' ', 'o', 'u', 't', 'l', 'i', 'n', 'e', 's', ' ', 't', 'h', 'e', ' ', 'f', 'e', 'a', 't', 'u', 'r', 'e', 's', ' ', 'f', 'o', 'r', ' ', 'B', 's', '4', ',', ' ', 'r', 'e', 'q', 'u', 'e', 's', 't', 's', ',', ' ', 'a', 'n', 'd', ' ', 's', 'e', 'l', 'e', 'n', 'i', 'u', 'm', ' ', 't', 'o', ' ', 's', 'c', 'r', 'a', 'p', 'e', ' ', 'o', 'r', ' ', 'r', 'e', 'v', 'e', 'r', 's', 'e', ' ', 'e', 'n', 'g', 'i', 'n', 'e', 'e', 'r', ' ', 'w', 'e', 'b', 's', 'i', 't', 'e', 's', '.', ' ', 'G', 'i', 'v', 'e', ' ', 'u', 's', 'e', ' ', 'c', 'a', 's', 'e', 's', ' ', 'w', 'h', 'e', 'n', ' ', 'e', 'a', 'c', 'h', ' ', 'i', 's', ' ', 't', 'h', 'e', ' ', 'p', 'r', 'e', 'f', 'e', 'r', 'r', 'e', 'd', ' ', 't', 'o', 'o', 'l', ',', ' ', 'w', 'h', 'e', 'n', ' ', 't', 'o', ' ', 'c', 'o', 'm', 'b', 'i', 'n', 'e', ' ', 't', 'h', 'e', 'm', ',', ' ', 'a', 'n', 'd', ' ', 'h', 'o', 'w', ' ', 't', 'o', ' ', 'a', 'c', 'h', 'i', 'e', 'v', 'e', ' ', 's', 'p', 'e', 'c', 'i', 'f', 'i', 'c', ' ', 'g', 'o', 'a', 'l', 's', '.', ' ', 'P', 'r', 'o', 'v', 'i', 'd', 'e', ' ', 'w', 'h', 'e', 'n', ' ', 'e', 'a', 'c', 'h', ' ', 'i', 's', ' ', 't', 'y', 'p', 'i', 'c', 'a', 'l', 'l', 'y', ' ', 'u', 's', 'e', 'd', ':', ' ', 'r', 'e', 'v', 'e', 'r', 's', 'e', ' ', 'e', 'n', 'g', 'i', 'n', 'e', 'e', 'r', ' ', 'w', 'e', 'b', 's', 'i', 't', 'e', 's', ' ', 'a', 'n', 'd', ' ', 'o', 't', 'h', 'e', 'r', ' ', 't', 'i', 'm', 'e', 's', ' ', 'i', 't', ' ', 'i', 's', ' ', 't', 'o', ' ', 'p', 'a', 'r', 's', 'e', ' ', 'a', 'r', 't', 'i', 'c', 'l', 'e', 's', ' ', 'a', 'n', 'd', ' ', 's', 'a', 'v', 'e', ' ', 't', 'h', 'e', 'm', ' ', 'w', 'h', 'e', 'n', ' ', 't', 'h', 'e', 'y', ' ', 'a', 'r', 'e', ' ', 'r', 'e', 'l', 'e', 'v', 'a', 'n', 't', ' ', 't', 'o', ' ', 'm', 'y', ' ', 'r', 'e', 's', 'e', 'a', 'r', 'c', 'h', '.']
API Budget: infinite
Continue (y/n): n

### Current behavior 😯

Goals: ['A', 's', ' ', 'a', 'n', ' ', 'A', 'I', ' ', 'w', 'e', 'b', ' ', 'g', 'u', 'r', 'u', ',', ' ', 'y', 'o', 'u', ' ', 'w', 'a', 'n', 't', ' ', 't', 'o', ' ', 'w', 'r', 'i', 't', 'e', ' ', 'a', ' ', 'b', 'l', 'o', 'g', ' ', 'a', 'r', 't', 'i', 'c', 'l', 'e', ' ', 't', 'h', 'a', 't', ' ', 'o', 'u', 't', 'l', 'i', 'n', 'e', 's', ' ', 't', 'h', 'e', ' ', 'f', 'e', 'a', 't', 'u', 'r', 'e', 's', ' ', 'f', 'o', 'r', ' ', 'B', 's', '4', ',', ' ', 'r', 'e', 'q', 'u', 'e', 's', 't', 's', ',', ' ', 'a', 'n', 'd', ' ', 's', 'e', 'l', 'e', 'n', 'i', 'u', 'm', ' ', 't', 'o', ' ', 's', 'c', 'r', 'a', 'p', 'e', ' ', 'o', 'r', ' ', 'r', 'e', 'v', 'e', 'r', 's', 'e', ' ', 'e', 'n', 'g', 'i', 'n', 'e', 'e', 'r', ' ', 'w', 'e', 'b', 's', 'i', 't', 'e', 's', '.', ' ', 'G', 'i', 'v', 'e', ' ', 'u', 's', 'e', ' ', 'c', 'a', 's', 'e', 's', ' ', 'w', 'h', 'e', 'n', ' ', 'e', 'a', 'c', 'h', ' ', 'i', 's', ' ', 't', 'h', 'e', ' ', 'p', 'r', 'e', 'f', 'e', 'r', 'r', 'e', 'd', ' ', 't', 'o', 'o', 'l', ',', ' ', 'w', 'h', 'e', 'n', ' ', 't', 'o', ' ', 'c', 'o', 'm', 'b', 'i', 'n', 'e', ' ', 't', 'h', 'e', 'm', ',', ' ', 'a', 'n', 'd', ' ', 'h', 'o', 'w', ' ', 't', 'o', ' ', 'a', 'c', 'h', 'i', 'e', 'v', 'e', ' ', 's', 'p', 'e', 'c', 'i', 'f', 'i', 'c', ' ', 'g', 'o', 'a', 'l', 's', '.', ' ', 'P', 'r', 'o', 'v', 'i', 'd', 'e', ' ', 'w', 'h', 'e', 'n', ' ', 'e', 'a', 'c', 'h', ' ', 'i', 's', ' ', 't', 'y', 'p', 'i', 'c', 'a', 'l', 'l', 'y', ' ', 'u', 's', 'e', 'd', ':', ' ', 'r', 'e', 'v', 'e', 'r', 's', 'e', ' ', 'e', 'n', 'g', 'i', 'n', 'e', 'e', 'r', ' ', 'w', 'e', 'b', 's', 'i', 't', 'e', 's', ' ', 'a', 'n', 'd', ' ', 'o', 't', 'h', 'e', 'r', ' ', 't', 'i', 'm', 'e', 's', ' ', 'i', 't', ' ', 'i', 's', ' ', 't', 'o', ' ', 'p', 'a', 'r', 's', 'e', ' ', 'a', 'r', 't', 'i', 'c', 'l', 'e', 's', ' ', 'a', 'n', 'd', ' ', 's', 'a', 'v', 'e', ' ', 't', 'h', 'e', 'm', ' ', 'w', 'h', 'e', 'n', ' ', 't', 'h', 'e', 'y', ' ', 'a', 'r', 'e', ' ', 'r', 'e', 'l', 'e', 'v', 'a', 'n', 't', ' ', 't', 'o', ' ', 'm', 'y', ' ', 'r', 'e', 's', 'e', 'a', 'r', 'c', 'h', '.']
API Budget: infinite
Continue (y/n): n

### Expected behavior 🤔

that the goals are a json objects 

### Your prompt 📝

```yaml
# Paste your prompt here
ai_goals:
- Provide expert advice on when to use Bs4, requests, and selenium for web scraping
  and reverse engineering websites based on specific use cases.
- Identify and prioritize the most effective tools and techniques to achieve specific
  goals, such as parsing articles, creating datasets, or capturing screenshots of
  web UI configurations.
- Proactively suggest ways to combine different tools and techniques to maximize results
  and minimize time and effort.
- Engage in effective problem-solving, prioritization, planning, and supporting execution
  to address your web scraping and reverse engineering needs as your virtual assistant.
- Provide specific, actionable, and concise advice to help you make informed decisions
  without the use of platitudes or overly wordy explanations.
ai_name: WebScrapeGPT
ai_role: an AI agent that specializes in web scraping and reverse engineering websites
  to help researchers, data scientists, and developers extract valuable information
  and create datasets for machine learning models.
api_budget: 0.0
```

### Your Logs 📒

```log
<i apologize for the inconvenience. Please use the "write_to_file" command to create a new file and start writing your report. You can use the information from the NSX Reference Design Guide documentation on NSX-T SDN overlay network components to write your report.
2023-05-16 09:14:59,875 ERROR logs:_log:143 The JSON object is invalid. 
2023-05-16 09:17:07,217 ERROR logs:_log:143 The JSON object is invalid. 
2023-05-17 10:50:06,597 ERROR logs:_log:143 The JSON object is invalid. 
2023-05-17 10:50:37,202 ERROR logs:_log:143 The JSON object is invalid. 
2023-05-17 11:02:00,221 ERROR logs:_log:143 Error: The following AI output couldn't be converted to a JSON:
 {
    "
2023-05-17 11:02:29,160 ERROR logs:_log:143 Error: The following AI output couldn't be converted to a JSON:
 {
    "
2023-05-17 11:02:44,778 ERROR logs:_log:143 Error: The following AI output couldn't be converted to a JSON:
 {
    "
2023-05-17 11:09:15,887 ERROR logs:_log:143 The JSON object is invalid. e>
```
