### ISSUE TITLE
AutoGPT fails to follow commands for analysing the contents of a local directory [full logs attached]

### ISSUE THREAD

**Issue by pax-k** [Significant-Gravitas/Auto-GPT#4425]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

I placed the source code of llamaindex in `auto_gpt_workspace/llamaindex` and asked AutoGPT to analyse the source code, but it fails to do so:
- uses a browser even if i'm trying hard not to make it use a browser
- fails to understand from the start that it should use local commands to traverse the llamaindex project
- even when it uses commands, it gets them wrong or tries to open the wrong files

This is my docker-compose.yml:

```
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      - ./logs:/app/logs
      - type: bind
        source: ./prompt_settings.yaml
        target: /app/prompt_settings.yaml
      - type: bind
        source: ./ai_settings.yaml
        target: /app/ai_settings.yaml
  redis:
    image: "redis/redis-stack-server:latest"
```
This is my .env file:

```
EXECUTE_LOCAL_COMMANDS=True
RESTRICT_TO_WORKSPACE=True
AI_SETTINGS_FILE=ai_settings.yaml
PROMPT_SETTINGS_FILE=prompt_settings.yaml
ALLOW_COMMANDS=cd,ls,cat,grep,find,python
MEMORY_BACKEND=json_file
MEMORY_INDEX=auto-gpt-memory
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
WIPE_REDIS_ON_START=True
```

This is my prompt_settings.yaml:

```
constraints: [
  '~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files.',
  'If you are unsure how you previously did something or want to recall past events, thinking about similar events will help you remember.',
  'No user assistance',
  'Exclusively use the commands listed below e.g. command_name'
]
resources: [
  'Filesystem access for searches and information gathering.',
  'Long Term memory management.',
  'GPT-3.5 powered Agents for delegation of simple tasks.',
  'File output.'
]
performance_evaluations: [
  'Continuously review and analyze your actions to ensure you are performing to the best of your abilities.',
  'Constructively self-criticize your big-picture behavior constantly.',
  'Reflect on past decisions and strategies to refine your approach.',
  'Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.',
  'Write all code to a file.'
]
```

This is my ai_settings.yaml:

```
ai_goals:
- Analyze the LlamaIndex source code using local filesystem commands to identify and extract relevant information about
  the library's functionality and usage.
- Provide clear and concise explanations of the purpose and functionality of the LlamaIndex
  library, including its various modules and functions.
- Answer questions and provide solutions for common issues and errors that may arise
  when using the LlamaIndex library, including troubleshooting and debugging support.
- Assist with integrating the LlamaIndex library into existing Python projects, including
  providing guidance on best practices and potential pitfalls to avoid.
- Never use a browser or the internet to answer questions or provide solutions.
ai_name: LlamaIndexGPT
ai_role: an AI assistant that knows Python, how to use linux commands to interact with the filesystem, opens files, analyzes file contents, provides guidance and support for using the locally hosted LlamaIndex Python library, including answering questions and providing explanations about the library's functionality and usage.
api_budget: 0.0
```

### Upload Activity Log Content

https://gist.github.com/pax-k/9b7c59eeebdf27fb47878bb9243643f3

### Upload Error Log Content

https://gist.github.com/pax-k/87abc7bbf920079008c4d99789054a27
