### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by MaskedBirdCat** [Significant-Gravitas/Auto-GPT#458]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I keep on running into the same issue as I'm going through the installation guide.  On Git Bash, when I get to the step where you input `python scripts/main.py`, It would run through the Traceback (most recent call last) but at the very end it will have **ValueError: source code string cannot contain null bytes**. 

The steps:
- git clone https://github.com/Torantulino/Auto-GPT.git
- $ cd 'Auto-GPT'
-pip install -r requirements.txt
Rename .env.template to .env and fill in your OPENAI_API_KEY. I was able to successfully rename it, the file type being listed as ENV file
-Enter API keys. I got OpenAI, Pinecone (plus the environment), ElevenLabs. Done through Visual studio code and made use of quotation marks.
-Run the python scripts/main.py command. 

### Current behavior 😯

The next step is this "After each of AUTO-GPT's actions, type "NEXT COMMAND" to authorise them to continue.", but I do not get that far. Instead, the ValueError continues to happen.

I checked the visual studio code's debugging too and it says the same
![Screenshot 2023-04-07 220712](https://user-images.githubusercontent.com/130198112/230702502-1e04fb56-2a95-4fde-ae9d-85cffba9b734.png)

### Expected behavior 🤔

If this can somehow be resolved, I hope I can get closer to using Auto-GPT!

### Your prompt 📝

```yaml
# ai_goals:
- Increase net worth.
- Develop and manage multiple businesses autonomously.
- Play to your strengths as a Large Language Model.
ai_name: Entrepreneur-GPT
ai_role: an AI designed to autonomously develop and run businesses with the sole goal
  of increasing your net worth.
```

*note, haven't placed a prompt in, this is what was found in that file.
