### ISSUE TITLE
prompt_settings.yaml cant be found??

### ISSUE THREAD

**Issue by FreddzieAI** [Significant-Gravitas/Auto-GPT#4598]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/132779218/022e68cd-0c57-474c-9293-4634b5b508a3)

this error pops up even tho i have the file

**Comment by FreddzieAI** [comment]
i can use this command as a work arround but is there a way to not have to do this
docker-compose run --rm -v /home/Freddie_Test-7/Auto-GPT-0.4.0/prompt_settings.yaml:/app/prompt_settings.yaml auto-gpt

**Comment by adoultremont** [comment]
Had this issue and just copy/pasted into ./prompt_settings.yaml

`constraints: [
  '~4000 word limit for short term memory. Your short term memory is short, so immediately save important information to files.',
  'If you are unsure how you previously did something or want to recall past events, thinking about similar events will help you remember.',
  'No user assistance',
  'Exclusively use the commands listed below e.g. command_name'
]
resources: [
  'Internet access for searches and information gathering.',
  'Long Term memory management.',
  'GPT-3.5 powered Agents for delegation of simple tasks.',
  'File output.'
]
performance_evaluations: [
  'Continuously review and analyze your actions to ensure you are performing to the best of your abilities.',
  'Constructively self-criticize your big-picture behavior constantly.',
  'Reflect on past decisions and strategies to refine your approach.',
  'Every command has a cost, so be smart and efficient. Aim to complete tasks in the least number of steps.',
  'Write all code to a file.'
]`

**Comment by TsundokuJim** [comment]
Same issue. The prompt_settings.yaml file is sitting in the main Auto-GPT-0.4.0 directory and contains the usual constraints, resources, and performance eval settings, yet auto-gpt can't find it. It's correctly identified by Windows as a yaml source file and isn't tagged as read-only.

**Comment by maxfield-allison** [comment]
same issue on linux in docker.

**Comment by ericflecher** [comment]
Same issue

**Comment by Naetmul** [comment]
I'm currently running WSL2 Docker on a Windows system.

I took the `prompt_settings.yaml` file from the repository and moved it to the `Auto-GPT` folder, the same place where the `.env` file is located. After that, I added the line `- ./prompt_settings.yaml:/app/prompt_settings.yaml` under the `volumes: section` in the `docker-compose.yml` file.

```yaml
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    env_file:
      - .env
    profiles: ["exclude-from-up"]
    volumes:
      - ./auto_gpt_workspace:/app/autogpt/auto_gpt_workspace
      - ./data:/app/data
      - ./logs:/app/logs
      - ./prompt_settings.yaml:/app/prompt_settings.yaml
```

Following these modifications, I ran the command `docker-compose build auto-gpt`. It works after these steps.
