### ISSUE TITLE
plugins not loadings. 

### ISSUE THREAD

**Issue by Bobolx00** [Significant-Gravitas/Auto-GPT#4780]
auto-gpt-auto-gpt-1  |   Not loading plugin AutoGPTWikipediaSearch as it was not found in config. Please check your config. Starting with 0.4.1, plugins will not be loaded unless they are enabled in plugins_config.yaml. Zipped plugins should use the class name (AutoGPTWikipediaSearch) as the key.

what template plugins_config.yaml should have?

**Comment by kolinko** [comment]
Yeah, it's not documented well...

Example plugins_config.yaml:
```
AutoGPTWolframAlphaSearch:
  config: {}
  enabled: true

PlannerPlugin:
  config: {}
  enabled: true

AutoGPTWikipediaSearch:
  config: {}
  enabled: true
```
