### ISSUE TITLE
Error when generating images using SD

### ISSUE THREAD

**Issue by Jpkovas** [Significant-Gravitas/Auto-GPT#513]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Ask for Auto GPT to create a image, using sd in the .env

### Current behavior 😯

The Auto-GPT got this error when tried to use generate_image command: 
Command generate_image returned: Error: cannot identify image file <_io.BytesIO object at 0x000001DF7156E3E0>

### Expected behavior 🤔

Save a image to auto_gpt_workspace folder

### Your prompt 📝

```yaml
ai_goals:
- Create an image of a fox dancing
- shutdown
ai_name: Artist_AI
ai_role: an AI designed to create images
```
