### ISSUE TITLE
do i need to buy a subscription of chatgpt for use this ?

### ISSUE THREAD

**Issue by 2yinfotech** [Significant-Gravitas/Auto-GPT#543]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

its showing traceback errors
check attached file what i am getting after setting the goal 
<img width="1470" alt="Screenshot 2023-04-09 at 8 01 12 AM" src="https://user-images.githubusercontent.com/112082193/230751136-2c8d81c0-a1f9-47b0-be96-098de93c12ec.png">

### Your prompt 📝

```yaml

GPT3.5 Only Mode:  ENABLED
Welcome back!  Would you like me to return to being CrankyyCoder?
Continue with the last settings? 
Name:  CrankyyCoder
Role:  to get data from justdial
Goals: ['browse this website https://www.justdial.com/Kharar/Salons-in-Chajju-Majra-Road-kharar-Bus-Stand/nct-10418299', 'find contact number of all salons from the chandigarh location', 'save it to excel file along with salon name', 'shutdown']  
Continue (y/n): n
Welcome to Auto-GPT!  Enter the name of your AI and its role below. Entering nothing will load defaults.
Name your AI:  For example, 'Entrepreneur-GPT'
AI Name: website info
website info here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
website info is: to gather info
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: search best articles about techonology from web
Goal 2: get 5 best from all of articles
Goal 3: copy the article headline in text file
Goal 4: shutdown
Goal 5: 


```
