### ISSUE TITLE
Tries to run python scripts that it hasn't created yet

### ISSUE THREAD

**Issue by hughperkins** [Significant-Gravitas/Auto-GPT#608]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

```
AI Name: programmer-gpt
programmer-gpt here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
programmer-gpt is: an AI that will code a website for me, in React, with a python backend. The website will let me make requests to openai for completions. Importantly, if the completion contains any files, those files will show up in a hierarchical tree view on the left hand side, with the filenames. If I click on any filename, I can see the contents in a modal popup. The rest of the completion will display elsewhere.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: fulfil your role
Goal 2: create the files for this website
Goal 3:
Using memory of type: LocalCache
PROGRAMMER-GPT THOUGHTS: I think we should start by creating the file structure for the website including React and Python backends.
REASONING: By creating the file structure, we can properly organize and establish the foundation of the website before proceeding to the specific website features.
PLAN:
-  Set up folders for React and Python backends
-  Create files for required dependencies
-  Initialize file directories
-  Start React and Python backends
-  Confirm successful operation after iteration
-  Create web interface
CRITICISM: I can easily get lost in the details and forget the big-picture goal. I'll need to step back and review regularly to make sure we are on track.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'structure.txt', 'text': 'File Structure:\n- Create React and Python Backend\n- Set up folders for React and Python backends\n- Create files for required dependencies\n- Initialize file directories\n- Start React and Python backends\n- Confirm successful operation after iteration\n- Create web interface'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for programmer-gpt...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command write_to_file returned: File written to successfully.
PROGRAMMER-GPT THOUGHTS: Now that we have created the file structure in our 'structure.txt' file, we should start setting up the folders for the React and Python backends.
REASONING: Setting up separate folders for the React and Python backends will allow us to keep their respective files organized and easy to manage.
PLAN:
-  Create a 'react-backend' folder
-  Create a 'python-backend' folder
-  Move the necessary files for each backend to their respective folders
CRITICISM: I'll need to be mindful of the dependencies between the two backends and the potential need for shared code that could be housed in a separate folder.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'create_folders.py'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for programmer-gpt...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
Executing file 'create_folders.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: File 'create_folders.py' does not exist.
```

### Current behavior 😯

states the commands it should run

Then decides to run a python script, with a made up main, that it hasnt actually created yet

### Expected behavior 🤔

should probably either create a shell script first, containing the commands, then run that; or else just run each command one at a time, rahter than putting them in a script. either way seems ok for me.

### Your prompt 📝

```yaml
AI Name: programmer-gpt
programmer-gpt here! I am at your service.
Describe your AI's role:  For example, 'an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.'
programmer-gpt is: an AI that will code a website for me, in React, with a python backend. The website will let me make requests to openai for completions. Importantly, if the completion contains any files, those files will show up in a hierarchical tree view on the left hand side, with the filenames. If I click on any filename, I can see the contents in a modal popup. The rest of the completion will display elsewhere.
Enter up to 5 goals for your AI:  For example: Increase net worth, Grow Twitter Account, Develop and manage multiple businesses autonomously'
Enter nothing to load defaults, enter nothing when finished.
Goal 1: fulfil your role
Goal 2: create the files for this website
Goal 3:
Using memory of type: LocalCache
PROGRAMMER-GPT THOUGHTS: I think we should start by creating the file structure for the website including React and Python backends.
REASONING: By creating the file structure, we can properly organize and establish the foundation of the website before proceeding to the specific website features.
PLAN:
-  Set up folders for React and Python backends
-  Create files for required dependencies
-  Initialize file directories
-  Start React and Python backends
-  Confirm successful operation after iteration
-  Create web interface
CRITICISM: I can easily get lost in the details and forget the big-picture goal. I'll need to step back and review regularly to make sure we are on track.
NEXT ACTION:  COMMAND = write_to_file ARGUMENTS = {'file': 'structure.txt', 'text': 'File Structure:\n- Create React and Python Backend\n- Set up folders for React and Python backends\n- Create files for required dependencies\n- Initialize file directories\n- Start React and Python backends\n- Confirm successful operation after iteration\n- Create web interface'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for programmer-gpt...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command write_to_file returned: File written to successfully.
PROGRAMMER-GPT THOUGHTS: Now that we have created the file structure in our 'structure.txt' file, we should start setting up the folders for the React and Python backends.
REASONING: Setting up separate folders for the React and Python backends will allow us to keep their respective files organized and easy to manage.
PLAN:
-  Create a 'react-backend' folder
-  Create a 'python-backend' folder
-  Move the necessary files for each backend to their respective folders
CRITICISM: I'll need to be mindful of the dependencies between the two backends and the potential need for shared code that could be housed in a separate folder.
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'create_folders.py'}
Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for programmer-gpt...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
Executing file 'create_folders.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: File 'create_folders.py' does not exist.
```
