### ISSUE TITLE
Azure implementation unable to provide required parameter

### ISSUE THREAD

**Issue by Rokniel** [Significant-Gravitas/Auto-GPT#657]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Fill out .env with required config as per https://pypi.org/project/openai/ and set USE_AZURE to True
2. Run main.py
3. Answer 'y' to execute default behaviour

### Current behavior 😯

After executing I immediately receive the error (adding initial lines for extra context):

Welcome back!  Would you like me to return to being Entrepreneur-GPT?
Continue with the last settings? 
Name:  Entrepreneur-GPT
Role:  an AI designed to autonomously develop and run businesses with the sole goal of increasing your net worth.
Goals: ['Increase net worth.', 'Develop and manage multiple businesses autonomously.', 'Play to your strengths as a Large Language Model.']
Continue (y/n): y

Using memory of type: LocalCache
Traceback (most recent call last):
  File "H:\AI\Text\Auto-GPT\scripts\main.py", line 297, in <module>
    assistant_reply = chat.chat_with_ai(
  File "H:\AI\Text\Auto-GPT\scripts\chat.py", line 72, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-5:]), 10)
  File "H:\AI\Text\Auto-GPT\scripts\memory\local.py", line 102, in get_relevant
    embedding = get_ada_embedding(text)
  File "H:\AI\Text\Auto-GPT\scripts\memory\base.py", line 9, in get_ada_embedding
    return openai.Embedding.create(input=[text], model="text-embedding-ada-002")["data"][0]["embedding"]
  File "C:\Users\Kari\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "C:\Users\Kari\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "C:\Users\Kari\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

### Expected behavior 🤔

Auto-GPT runs as normal.

When I change the .env USE_AZURE to False and set my openai api key, the software works as expected.
The same behavior is exhibited on both windows and mac, on python versions 3.10 and 3.11 respectively.

### Your prompt 📝

```yaml
ai_goals:
- Find ways to increase cloud2 (https://www.cloud2.fi/) net worth.
- Play to your strengths as a Large Language Model.
- Find ways to increase the value of cloud2 to their customers.
- Find new products that would help cloud2 increase its net worth.
ai_name: Entrepreneur-GPT
ai_role: an AI designed to autonomously develop and run businesses with the sole goal
  of increasing cloud2 net worth.
```
