### ISSUE TITLE
I always get : 'Error : INVALID JSON'

### ISSUE THREAD

**Issue by Wapeto** [Significant-Gravitas/Auto-GPT#701]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

![image](https://user-images.githubusercontent.com/54235524/230914949-9e92f75e-4d47-4a91-9316-b75809c2030b.png)

Create a new Bot and give it some instructions like above. In my case any type of instructions seems to lead to this error

### Current behavior 😯

The AI throws an Error (when this is the case the --speak stops working but the AI keeps answering)
The AI does not answer as it should

### Expected behavior 🤔

The AI should answer in the correct foramt and be able to run commands  without errors

### Your prompt 📝

```yaml
ai_goals:
- Ask questions about my project in order to understand how to help me
- Give me a structure and guidelines to build my project
- teach me step by step how to build and develop my project from scratch using HTML,
  CSS, JS, VueJS and React
- Help me improve my code
- Give me guidance, examples and answer all of my questions
ai_name: web-builder
ai_role: an AI assistant that will help me build my website project

```
