### ISSUE TITLE
Error creating Redis search index:  Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by hanskraut31312312** [Significant-Gravitas/Auto-GPT#715]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Just ran the autoGPT it worked this morning until now but now it does not work anymore i have not changed anything as far as i know maybe it was a update from git desktop a pull maybe

### Current behavior 😯

C:\Programming\Auto_GPT_AI_3>python scripts/main.py --gpt3only --speak
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Request failed with status code: 401
Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 16 characters remaining, while 65 characters are required for this request.","character_used":10049,"character_limit":10000}}'
Welcome back!  Would you like me to return to being Coder_GPT_3?
Continue with the last settings?
Name:  Coder_GPT_3
Role:  developing and improving a L.M.-A.I. that can improve itself automaticlly, runing on the Users pc, that he can talk to in natural language.
Goals: ['Experiment with ways to organize the development (Ideas: Lists, flowcharts, numbers, programs, foldersystems, natural language etc.). Test effectiveness.', 'Plan with the help of other agents systems to make use of cooperating agents. Create new agents to experiment with different approaches that can also create agents. Make sure there are not too many agents that might crash AutoGPT.', 'Experiment alone or by delegating to other agents how to plan the development in different layers and levels. Create agents to keep track.', 'Cretea a few agents that specialize on creating code for different aspects of the project.', 'Create a agent that creates a new agent that starts monitoring and trying to fix when a crash, issue or problem with continuing the development after a shutdown occurs. Create another one that monitors the overall progress every periodically rarely tracks if the last actions before a shutdown are continued when restarting, if not that agent should create 1 agent to help with that.']
Continue (y/n): y
Error creating Redis search index:  Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
Traceback (most recent call last):
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 698, in connect
    sock = self.retry.call_with_retry(
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 699, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 987, in _connect
    raise err
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 975, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/main.py", line 311, in <module>
    memory = get_memory(cfg, init=True)
  File "C:\Programming\Auto_GPT_AI_3\scripts\memory\__init__.py", line 30, in get_memory
    memory = RedisMemory(cfg)
  File "C:\Programming\Auto_GPT_AI_3\scripts\config.py", line 19, in __call__
    cls._instances[cls] = super(
  File "C:\Programming\Auto_GPT_AI_3\scripts\memory\redismem.py", line 59, in __init__
    existing_vec_num = self.redis.get(f'{cfg.memory_index}-vec_num')
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\commands\core.py", line 1790, in get
    return self.execute_command("GET", name)
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 1442, in get_connection
    connection.connect()
  File "C:\Users\marco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\redis\connection.py", line 704, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

C:\Programming\Auto_GPT_AI_3>sudo apt-get update
'sudo' is not recognized as an internal or external command,
operable program or batch file.

C:\Programming\Auto_GPT_AI_3>docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest
docker: Error response from daemon: Conflict. The container name "/redis-stack-server" is already in use by container "0b045e503e2c6cb3e9799fc9b64ecdfb7589bfaa6d5434262bbf37dcec7332e1". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.

C:\Programming\Auto_GPT_AI_3>

### Expected behavior 🤔

Normally start like this morning. I have not installed or changed smth since. The json error loops without stop forcing ctrl+c have been occuring since 17:00 now its 19:00 yesterday and this morning everything ran smooth as butter exept the normal json errors and very rare crashes every 5 hours

### Your prompt 📝

```yaml
Speak Mode:  ENABLED
GPT3.5 Only Mode:  ENABLED
Request failed with status code: 401
Response content: b'{"detail":{"status":"quota_exceeded","message":"This request exceeds your quota. You have 16 characters remaining, while 65 characters are required for this request.","character_used":10049,"character_limit":10000}}'
Welcome back!  Would you like me to return to being Coder_GPT_3?
Continue with the last settings?
Name:  Coder_GPT_3
Role:  developing and improving a L.M.-A.I. that can improve itself automaticlly, runing on the Users pc, that he can talk to in natural language.
Goals: ['Experiment with ways to organize the development (Ideas: Lists, flowcharts, numbers, programs, foldersystems, natural language etc.). Test effectiveness.', 'Plan with the help of other agents systems to make use of cooperating agents. Create new agents to experiment with different approaches that can also create agents. Make sure there are not too many agents that might crash AutoGPT.', 'Experiment alone or by delegating to other agents how to plan the development in different layers and levels. Create agents to keep track.', 'Cretea a few agents that specialize on creating code for different aspects of the project.', 'Create a agent that creates a new agent that starts monitoring and trying to fix when a crash, issue or problem with continuing the development after a shutdown occurs. Create another one that monitors the overall progress every periodically rarely tracks if the last actions before a shutdown are continued when restarting, if not that agent should create 1 agent to help with that.']
Continue (y/n): y
```
