### ISSUE TITLE
Can't execute py files on WSL

### ISSUE THREAD

**Issue by nicholmikey** [Significant-Gravitas/Auto-GPT#828]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

1. Install Auto-GPT in a folder in Ubuntu in WSL2
2. Ask Auto-GPT to write a python file 
3. See the system create the file successfully 
4. See the system fail to execute the file 

PLAN: 
-  Execute the Python file
CRITICISM: None
NEXT ACTION:  COMMAND = execute_python_file ARGUMENTS = {'file': 'ontario_sales_tax_calculator.py'}
Executing file 'ontario_sales_tax_calculator.py' in workspace 'auto_gpt_workspace'
SYSTEM:  Command execute_python_file returned: Error: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

### Current behavior 😯

Even though files can be created successfully and seen in the workspace folder, they can not be executed 

### Expected behavior 🤔

Files should execute 

### Your prompt 📝

```yaml
ai_goals:
- 'calculate Ontario sales tax on an amount entered '
- 'write a python file that prompts the user for an amount then returns an amount
  with Ontario sales tax applied '
ai_name: tax-GPT
ai_role: a tax calculating AI for Ontario sales tax

```
