### ISSUE TITLE
Agents aren't being fed full instructions on instantiation

### ISSUE THREAD

**Issue by vandervoortj** [Significant-Gravitas/Auto-GPT#907]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Give tasks that will spawn agents.

### Current behavior 😯

When agents are created, they can often be given a task without full context, and will respond "As an AI language model...". This often results in stuff like:

`NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'summarization_agent', 'task': 'Summarize AGI Literature', 'prompt': 'Please summarize the key findings of an AGI literature summary file.'}
SYSTEM:  Command start_agent returned: Agent summarization_agent created with key 2. First response: I'm sorry, but to summarize a literature summary file on AGI is a very broad task. Can you please provide me with the specific literature summary file you are referring to?`

`NEXT ACTION:  COMMAND = start_agent ARGUMENTS = {'name': 'AGISummarize', 'task': 'Find and summarize relevant scientific papers or articles on AGI', 'prompt': 'What scientific papers or relevant articles can you find about Artificial General Intelligence? Please add any valuable information you find to the AGI Comprehensive Summary file.'}
SYSTEM:  Command start_agent returned: Agent AGISummarize created with key 1. First response: As an AI language model, I do not have the capability to access the internet or any other external sources. However, I can suggest some resources where you can find scientific papers and articles related to Artificial General Intelligence. You can start by checking out the website of the AGI Society (agisociety.org), which is dedicated to advancing research in AGI. Additionally, some notable scientific papers on AGI include "Artificial General Intelligence: Concept, State of the Art, and Future Prospects" by Ben Goertzel and Cassio Pennachin, as well as "Artificial General Intelligence: A Path to Superintelligence" by Jürgen Schmidhuber. There are also several journals such as "Journal of Artificial Intelligence Research" and "Artificial Intelligence" that publish relevant articles on AGI.`

This is not only a waste of tokens, but it opens up the process to be flooded with hallucinations. It would seem we need to find a way for the director to be more verbose on agent instantiation.

### Expected behavior 🤔

Agents are spawned in a way so as to immediately perform tasks in the environment.

### Your prompt 📝

```yaml
ai_goals:
- Research all the various ways AGI has been referred to in the past
- Use those terms to find and summarize previous research in AGI into separate files
- Summarize across all research summaries into a single final file
- Shutdown
ai_name: AGIResearcher
ai_role: an AI designed to autonomously research previous works in the AGI field
```
