### ISSUE TITLE
Command execute_command_chain returned: Unknown command 'execute_command_chain'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

### ISSUE THREAD

**Issue by GhostfireZA** [Significant-Gravitas/Auto-GPT#949]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Just ask it to clone a git repository

Goal1: Clone, review, and clean the code: Clone the target project from my GitHub account at [GitHub here]  and analyze the source code and remove any unused or unnecessary code elements.

### Current behavior 😯

PLAN:
-  Clone the GitHub repository using the 'git clone' command.
-  Verify that the clone was successful using the 'ls' command.

CRITICISM: We should remember to navigate to the desired directory before executing any the commands.

NEXT ACTION:  COMMAND = execute_command_chain ARGUMENTS = {'commands': [{'name': 'change_directory', 'args': {'directory': '~/'}}, {'name': 'make_directory', 'args': {'directory': 'projectX'}}, {'name': 'change_directory', 'args': {'directory': 'projectX'}}, {'name': 'git_clone', 'args': {'repository': '[The repo you specified]'}}, {'name': 'list_directory', 'args': {'directory': '.'}}]}

SYSTEM:  Command execute_command_chain returned: Unknown command 'execute_command_chain'. Please refer to the 'COMMANDS' list for available commands and only respond in the specified JSON format.

### Expected behavior 🤔

Well, it should not break

### Your prompt 📝

```yaml
Name:  Maker
Role:  a autonomous AI that acts as a Code Reviewer. Your main goals are to clone a specific GitHub repository.
Goals: ['Clone the target project from my GitHub account at https://github.com/Torantulino/Auto-GPT/ and then analyze the source code and remove any unused or unnecessary code elements.', 'Provide a comprehensive documentation of any modifications made to the original code. Organize the documentation into the sections outlined in the previous response.']
```
