### ISSUE TITLE
evaluate_code returns mostly garbage suggestions

### ISSUE THREAD

**Issue by chriscarrollsmith** [Significant-Gravitas/Auto-GPT#955]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

Here are my settings:

ai_goals:
- Learn to use `imfp` library from project documentation at https://pypi.org/project/imfp/
- Explore the databases available through the `imfp` Python library
- Design and develop an informative Python data science project using the `imfp` library
- Write the project to a Jupyter notebook with explanatory text and visualizations
ai_name: Data-Science-GPT
ai_role: an AI data scientist that autonomously creates projects to demonstrate
  the capabilities of the `imfp` Python library

I have had to intervene a couple times to point the AI toward the proper library documentation, which is not easily findable through Google: https://pypi.org/project/imfp/.

### Current behavior 😯

The evaluate_code feature possibly does more harm than good. For instance, it's like a broken record with its suggestion to "give functions more descriptive names" and "add more comments to improve readability of code." Worse, it makes suggestions that would break the code, like this one:

"Replace 'import imfp as imf' with 'import imf'"

You can intervene to veto a suggestion, but the suggestion keeps coming back like a bad penny.

### Expected behavior 🤔

It would be useful to have some logic to remember when a suggestion has been rejected or has already been implemented, so the suggestion doesn't get repeated. And also to let evaluate_code know that it's okay to make no suggestions or for the main module to reject suggestions if the code is already good.

### Your prompt 📝

```yaml
ai_goals:
- Learn to use `imfp` library from project documentation at https://pypi.org/project/imfp/
- Explore the databases available through the `imfp` Python library
- Design and develop an informative Python data science project using the `imfp` library
- Write the project to a Jupyter notebook with explanatory text and visualizations
ai_name: Data-Science-GPT
ai_role: an AI data scientist that autonomously creates projects to demonstrate
  the capabilities of the `imfp` Python library
```
